### ISSUE TITLE
Bug (?): Time Code max value does not match documentation?

### ISSUE THREAD

**Issue by johannesvollmer** [AcademySoftwareFoundation/openexr#1006]
Hi! I was reading in the Time Code file. But then I realized that I don't understand why it's working, as it seems to me like it should not work.

In this section:

https://github.com/AcademySoftwareFoundation/openexr/blob/931618b9088fd03ed4fe30cade55664da94a5854/src/lib/OpenEXR/ImfTimeCode.cpp#L212-L220

__Edit:__ In the header file `ImfTimeCode.h`, the range is specified to be `29`. Which works. The `.cpp` file checks for `59`. I assume this is a bug in the `.cpp` file and the check should actually use `29` as maximum value. This Issue should therefore be a bug report.

---
It says here the frame can be any value from 0 to 59. Also, you can see that the frame is stored in 6 bits (bit 0 to 5). This would be fine, as 6 bits can encode 64 distinct values in theory. But before packing, the value is converted to a binary-encoded decimal, because this is how the SMPTE standard works. This representation is slightly less efficient and requires more bits.

 If my calculations are correct, the value 46, when converted to binary-encoded decimal, [results in](https://onlinebinarytools.com/convert-decimal-to-bcd?input=46) the bit pattern `0100 0110`. This binary-encoded decimal representation requires seven bits, which is more bits than we have available for the frame value (we only have 6 bits). That's strange, as 46 should be possible, because it is smaller than 59. Does this mean that some of the higher frame value would overflow, losing data? Due to the nature of binary-encoded decimals, which simply translates each decimal digit into four bits, anything >= 40 will require seven bits or more.

Am I missing a piece of information? Were my calculations incorrect? Why does this work?

**Comment by johannesvollmer** [comment]
In [the first table on this website](https://www.wikiwand.com/en/Vertical_interval_timecode), the frame is supposed to have the range 0 - 29 at most. Is 29 or 59 the correct maximum frame?

**Comment by johannesvollmer** [comment]
After some investigation, I realized that in the header file `ImfTimeCode.h`, the range is specified to be `29`. Which should work. But the `.cpp` file checks for `59`. If there is a reason to use `59` instead of `29`, this should be documented. Therefore I conclude this is a bug in the `.cpp` file and the check should actually use `29` as maximum value. Will you accept a pull request?

**Comment by meshula** [comment]
Thanks for the catch, 29 would be correct ~ a PR would be great.

**Comment by johannesvollmer** [comment]
Anyways, does any software still use this SMTPE timecode? Or is it just a relict from analog times?
