### ISSUE TITLE
MultiPartInputFile::header doesn't check for out-of-bounds access

### ISSUE THREAD

**Issue by anderslanglands** [AcademySoftwareFoundation/openexr#1031]
Should it throw Iex::ArgExc? Or at least use `at()`?

https://github.com/AcademySoftwareFoundation/openexr/blob/a00575feb645189354097d9b8808aa3030a800b0/src/lib/OpenEXR/ImfMultiPartInputFile.cpp#L194
```c++
const Header & MultiPartInputFile::header(int n) const { return _data->_headers[n]; }
```

**Comment by peterhillman** [comment]
That seems sensible. All methods in MultiPartInputFile and MultiPartOutputFile that take a part number should do bounds checking. Throwing ArgExc would be better than just using `at()`, so a more informative error message can be thrown and negative values for `n` can be handled.
