### ISSUE TITLE
-fsanitize=undefined link error

### ISSUE THREAD

**Issue by cary-ilm** [AcademySoftwareFoundation/openexr#1039]
Building with g++9.3 or clang10 with -fsanitize=undefined, OpenEXRTest is getting a link error:

/usr/bin/ld: CMakeFiles/OpenEXRTest.dir/testExistingStreams.cpp.o:(.data.rel+0x218): undefined reference to `typeinfo for Imf_3_0::TiledRgbaInputFile'

Any clues what might be causing this?

**Comment by meshula** [comment]
In my experience that's usually caused by an unresolved virtual function. e.g. 

```cpp
struct Foo { virtual void func() = 0; }
struct Bar : public Foo {}
```
but I'm not aware of any issues like that in OpenEXR...

**Comment by kdt3rd** [comment]
fyi, submitted a PR to fix this
