### ISSUE TITLE
refinement of how the code works

### ISSUE THREAD

**Issue by ihsinme** [AcademySoftwareFoundation/openexr#1059]
good day.
could you please clarify.
at this point are you expecting an exception to be thrown or just a text alert?

https://github.com/AcademySoftwareFoundation/openexr/blob/0d7e229c31db294489749217ff4d571f5a6a8249/src/lib/OpenEXR/ImfIDManifest.cpp#L337

**Comment by meshula** [comment]
That code is throwing an exception, because the IDManifest has been found to be in an unknown format. A calling program would need to take an appropriate action, such as catching the exception and showing a text alert.

**Comment by ihsinme** [comment]
shouldn't we add the word `throw` in this case?

**Comment by cary-ilm** [comment]
You're right, that line is indeed missing a throw. It simply constructs the exception object and then it goes out of scope without being thrown, clearly an oversight. Good catch.

**Comment by cary-ilm** [comment]
Fixed #1062.

**Comment by meshula** [comment]
haha, thanks for clarifying! I didn't notice the throw was missing! I have been looking at these macros too long and my brain filled in the blanks :)
