### ISSUE TITLE
ci installs boost and python. is this vestigial from Imath?

### ISSUE THREAD

**Issue by meshula** [AcademySoftwareFoundation/openexr#1101]
ci installs boost and python. is this vestigial from Imath?

Should those only be in Imath? The OpenEXR test suite is C++ based.

I think these should be removed unless there's some other dependency in the CI I can't spot.

**Comment by xlietz** [comment]
I don't believe it does but I may be missing something. For the Windows ci
builds, the scripts still exist in the repo but the lines that call them
are commented out in the CI. Similarly there are install scripts for Mac
that are not called by the Mac ci builds. If you were referring to the
existence of these scripts in the repo still, I can go ahead and delete
those unless anyone objects.

For Linux builds, the ci-openexr docker image has both Python and Boost.
That container is used by both openexr and imath. If that is the issue, we
can ask Aloys to make a separate docker container for Imath.

**Comment by meshula** [comment]
I'm not concerned about the docker images, in the future it might be good to have an Imath specific image but I don't think we're there yet. 

I'm just combing through the repo for boost and python references, and looking for things that can go away as a result of not using either in OpenEXR itself ~ so I think those ci support scripts should go. We need them in the Imath repo, but not here.

**Comment by xlietz** [comment]
These were removed in PR #1203 submitted by @Vertexwahn . Thanks again!
