### ISSUE TITLE
per-frame metadata missing from doc

### ISSUE THREAD

**Issue by ubyjvovk** [AcademySoftwareFoundation/openexr#1113]
Hi! It is my understanding that some cameras and renderers are able to embed metadata (such as focal length, exposure, etc) for every individual _frame_; however, the doc and examples seem to only mention _file-level headers_ (unless I'm misreading it completely). Is there a documented way to write custom per-frame attributes? If so, maybe the doc should explain it

**Comment by ubyjvovk** [comment]
apparently, exr is an image, not a sequence. TIL

**Comment by meshula** [comment]
Yes. A typical use case is a directory filled with numbered sequences of exr images, dumped out one by one by a renderer.
