### ISSUE TITLE
Interface link library Threads::Threads not required with glibc

### ISSUE THREAD

**Issue by hobbes1069** [AcademySoftwareFoundation/openexr#1121]
As of version 2.34 libpthread has been absorbed into glibc[1]:
`The glibc 2.34 release merges libpthread.so into libc.so and it would be important to remove DT_NEEDED on libpthread.so from all distribution binaries.`

However, the exported targets still include them:
```
grep Threads usr/lib64/cmake/OpenEXR/*
usr/lib64/cmake/OpenEXR/OpenEXRConfig.cmake:  find_dependency(Threads REQUIRED)
usr/lib64/cmake/OpenEXR/OpenEXRTargets.cmake:  INTERFACE_LINK_LIBRARIES "OpenEXR::IlmThreadConfig;OpenEXR::IlmThreadConfig;OpenEXR::Iex;Threads::Threads"
```

But since they are not getting expanded to a library name it is causing builds to fail  with `-lThreads::Threads` during linking.

[1] https://fedoraproject.org/wiki/Changes/GNUToolchainF35#Scope

**Comment by kdt3rd** [comment]
Could you validate that you have a recent / up-to-date version of cmake? We rely on find_package(Threads) to populate these flags. And as an interface library, at least in recent versions of cmake (I have 3.21), there is a check to see if libc includes pthread. If so, the link flags are not added (CMAKE_THREAD_LIBS_INIT should be ""), and only the addition of -pthread compile flag (which should still be needed).

Either way, thanks for the bug report - the detection for posix semaphores will be broken with this change (although all that will happen is the code will disable and use mutex + condition variable, which is not ideal, but should not cause errors).

**Comment by hobbes1069** [comment]
Yes, Fedora pretty much always has the latest release, 3.21.x at the time, but still showing `Theads::Threads`...

I just tried a build with cmake 3.21.2 and can confirm the problem is still present:
```
$ grep Threads::Threads usr/lib64/cmake/OpenEXR/*
usr/lib64/cmake/OpenEXR/OpenEXRTargets.cmake:  INTERFACE_LINK_LIBRARIES "OpenEXR::IlmThreadConfig;OpenEXR::IlmThreadConfig;OpenEXR::Iex;Threads::Threads"
```

**Comment by hobbes1069** [comment]
Poking around the cmake stuff I saw this in `src/lib/IlmThread/CMakeLists.txt`
```
if(OPENEXR_ENABLE_THREADING)
  target_link_libraries(IlmThread PUBLIC Threads::Threads)
endif()
```

May have nothing to do with the problem but it seems to require Threads::Threads regardless of glibc version?

I'm digging through the build system and in general I quite like CMake but it makes it easy to bury logic everywhere and I'm not sure I have the time to unravel it all at the moment.

**Comment by kdt3rd** [comment]
Yes, precisely. Threads::Threads is an "interface" library, cmake should not be adding the -lpthread (or a -l anything) in the case of pthread being in libc. The place to look is in /usr/share/cmake-\<version\>/Modules/FindThreads.cmake - that is the file that provides the Threads::Threads target in the first place, at least on my machine (I have cmake 3.21.2)

[where on systems where -lpthread is still needed, it will set a property saying it needs to link against that]

**Comment by hobbes1069** [comment]
The very end of the file seems to unconditionally create an empty `Threads::Threads` target and then only populates it if `CMAKE_THREAD_LIBS_INIT ` is non-empty.
```
if(THREADS_FOUND AND NOT TARGET Threads::Threads)
  add_library(Threads::Threads INTERFACE IMPORTED)

  if(THREADS_HAVE_PTHREAD_ARG)
    set_property(TARGET Threads::Threads
                 PROPERTY INTERFACE_COMPILE_OPTIONS "$<$<COMPILE_LANG_AND_ID:CUDA,NVIDIA>:SHELL:-Xcompiler -pthread>"
                                                    "$<$<NOT:$<COMPILE_LANG_AND_ID:CUDA,NVIDIA>>:-pthread>")
  endif()

  if(CMAKE_THREAD_LIBS_INIT)
    set_property(TARGET Threads::Threads PROPERTY INTERFACE_LINK_LIBRARIES "${CMAKE_THREAD_LIBS_INIT}")
  endif()
endif()
```

**Comment by hobbes1069** [comment]
There doesn't appear to be a good way of getting all of a targets properties in CMake but I found a script on stack exchange and got the following:
```
# cmake .
-- Using Imath from /usr/lib64/cmake/Imath
Threads::Threads IMPORTED = TRUE
Threads::Threads IMPORTED_GLOBAL = FALSE
Threads::Threads NAME = Threads::Threads
Threads::Threads TYPE = INTERFACE_LIBRARY
```
Not much in there...

I don't know why FindThreads creates an empty imported library, perhaps it would be better to test if the actual library name is specified?

**Comment by hobbes1069** [comment]
So I guess one question is where should this be fixed? In OpenEXR? Or in vigra?

I suppose logic could be added to the latter to also check for empty `CMAKE_THREAD_LIBS_INIT` before trying to link with an empty library?

**Comment by meshula** [comment]
Looping back around to the original issue, and acknowledging that in an ideal world kitware would make this less painful in their cmake find scripts, what about something like this on OpenEXR's side? (obv I didn't look up the real magic variable names)

```cmake
if(OPENEXR_ENABLE_THREADING AND COMPILER_NAME='gcc' AND GLIBC_VERSION < 2.34)
  target_link_libraries(IlmThread PUBLIC Threads::Threads)
endif()
```

**Comment by kdt3rd** [comment]
The "empty" interface library is fine (notice that yes, it is imported, but it is of type INTERFACE).

@meshula - we want that link always to add the -pthread argument, etc. so we should not elide that dependency.

There are 2 ways a -lThreads::Threads could be emitted:
- vigra is iterating over dependencies and arbitrarily adding a link, which it does not appear to do having the briefest of looks at their repo.
- the find_dependency(Threads REQUIRED) is not running when find_package(OpenEXR) is called, so there is no Threads::Threads interface target. Some of the generated code in OpenEXRConfig.cmake made me slightly suspicious, hence below

@hobbes1069 - I did find a potential issue, where the generated config that then is used by find_package(OpenEXR) would not preserve the THREADS_PREFER_PTHREAD_FLAG, which changes the behavior of FindThreads.cmake. There was also a potential issue with the generated config testing against the configuration variable for enabling threads or not. I have submitted a merge request (linked above). If you could test by editing the installed OpenEXRConfig.cmake (should be in /usr/lib/cmake/OpenEXR/OpenEXRConfig.cmake) and changing the lines around line 28 or so from:
if(ON)
  find_dependency(Threads REQUIRED)
endif()

to

set(openexr_needsthreads ON)
if(openexr_needsthreads)
  set(THREADS_PREFER_PTHREAD_FLAG ON)
  find_dependency(Threads REQUIRED)
endif()

and let me know if that works, that will fully validate the above fix. Thanks!

**Comment by hobbes1069** [comment]
I performed a simple rebuild with the pull request and rebuilt virga and it seems OK

https://copr.fedorainfracloud.org/coprs/hobbes1069/openexr/builds/

**Comment by kdt3rd** [comment]
great, good to hear, thanks for the report, and sorry for any initial confusion, I thought it was an error building exr itself, not in using it downstream, probably could have gotten there faster had I realized that...
