### ISSUE TITLE
Mirror/flip/upside down

### ISSUE THREAD

**Issue by vtushevskiy** [AcademySoftwareFoundation/openexr#1170]
What is the optimal way to flip the image by Y axis by using OpenEXR tools (if any)?
For example, when I read from OpenGL framebuffer with 'glMapBuffer()' and write it to EXR by default way and try to read it in Nuke, I get flipped image:
```
    Imf::setGlobalThreadCount (32);
    Imf::RgbaOutputFile file(fileName, width, height, Imf::WRITE_RGBA, 1,
                             IMATH_NAMESPACE::V2f(0, 0), 1, Imf::INCREASING_Y,
                             Imf::Compression(exrCompression));
    file.setFrameBuffer (pixels, 1, width);
    file.writePixels (height);
```
I have found brute force way to flip it by process my data but it is very slow.
```
Imf::Rgba *flippedPixels = new Imf::Rgba[width * height];
    for (int i = 0; i < height; i++)
    {
        for (int j = 0; j < width; j++)
        {
            // Set top scanline of flippedPixels to be bottom scanline of pixels
            flippedPixels[(((height - 1) - i) * width) + j] = pixels[(i * width) + j];
        }
    }
```
I understand that I can apply multithreading here but I don't want to make the task of simple Y-flipping too complex.
Is there some "standard" way how to flip my image? Something like STB library function "stbi_set_flip_vertically_on_load(bool)"???

**Comment by kdt3rd** [comment]
If you have a buffer in OpenGL order, which has y in lower left, so the beginning of the memory block is your upper left corner, don't you want to use DECREASING_Y to store this if you are using the Rgba output file buffer?

**Comment by cary-ilm** [comment]
Following up on this, did @kdt3rd's comment solve the issue? Closing for now, but if you have further questions, please re-open.
