### ISSUE TITLE
Can not get the same result by Render OpenEXR with OpenGL

### ISSUE THREAD

**Issue by klydeid** [AcademySoftwareFoundation/openexr#1188]
Hey guy.
I am newbee here. 
I am trying to create a simple software to show OpenEXR images.  I am using Qt5 and Opengl to create the preview.
But now i have a problem.
![image](https://user-images.githubusercontent.com/82641456/138423056-7cf9fb56-d655-4656-b648-44a002608a17.png)

the left one is a image view tool by Houdini.  and the right one is my preview.
it is very gray!

another sample:
![image](https://user-images.githubusercontent.com/82641456/138423835-0c33d76f-d08c-458f-9a5f-a4ec1ab8d1aa.png)

here is my setup. it is pretty basic

QImage HPImageLoader::exrProcess(){

    int width;
    int height;

    //   RGBAinputfile to read the file
    Imf::RgbaInputFile file(file_path.toStdString().c_str());
    //   get boundingbox
    Imath::Box2i dw = file.dataWindow();

    //   get X and Y resolution
    width = dw.max.x - dw.min.x + 1;
    height = dw.max.y - dw.min.y + 1;

    xres = width;
    yres = height;
    aspect_ratio = float(xres) / yres;

    //   use width and height to create QImage with same size
    QImage image(width, height, QImage::Format_RGB32);

    Imf::Array2D<Imf::Rgba> pixels;
    pixels.resizeErase(height, width);

    //   copy data to buffer
    file.setFrameBuffer(&pixels[0][0] - dw.min.x - dw.min.y * width, 1, width);
    file.readPixels(dw.min.y, dw.max.y);

    //   copy data to QImage
    for (int y = 0; y < height; y++) {
        for (int x = 0; x < width; x++) {
            image.setPixel(x, y, RgbaToQrgba(pixels[y][x]));
        }
    }

    //   return
    return image;
}

QRgb HPImageLoader::RgbaToQrgba(Imf_3_1::Rgba &imagePixel)
{

    float r;
    float g;
    float b;
    float a;

    r = imagePixel.r * 5.55555;
    g = imagePixel.g * 5.55555;
    b = imagePixel.b * 5.55555;
    a = imagePixel.a * 5.55555;

    if (r > 1.0) {
        r = 1.0 + std::log((r - 1.0) * 0.184874 + 1) / 0.184874;
    }
    if (g > 1.0) {
        g = 1.0 + std::log((g - 1.0) * 0.184874 + 1) / 0.184874;
    }
    if (b > 1.0) {
        b = 1.0 + std::log((b - 1.0) * 0.184874 + 1) / 0.184874;
    }
    if (a > 1.0) {
        a = 1.0 + std::log((a - 1.0) * 0.184874 + 1) / 0.184874;
    }

    double gamma = 1.0 / 2.2;
    r = std::pow(r, gamma);
    g = std::pow(g, gamma);
    b = std::pow(b, gamma);
    a = std::pow(a, gamma);

    return qRgba((unsigned char)(Imath::clamp(r * 84.66f, 0.f, 255.f)),
                 (unsigned char)(Imath::clamp(g * 84.66f, 0.f, 255.f)),
                 (unsigned char)(Imath::clamp(b * 84.66f, 0.f, 255.f)),
                 (unsigned char)(Imath::clamp(a * 84.66f, 0.f, 255.f)));

}

I use these two functions to load EXR file to a QImage and then render it with OpenGL.
and the RgbaToQrgba() function is copied from Github.  actually i don't know why to do this.  
so what is wrong with my code?

and it will be great if there are some basic samples for me. maybe this is too hard for a newbee coder  :(

Thanks!

**Comment by lgritz** [comment]
This is not an OpenEXR problem. The issue is surely one of color management.

First of all, you're doing some kind of logarithmic based tone mapping to reduce the range of your > 1.0 values, and then a gamma correction (note: gamma 2.2 is not quite the same as sRGB), and then a scale and clamp? Which I assume is not the same sequence that Houdini is doing when displaying the image.

Second, it's hard to know what kind of color space or viewing transforms are being used by Qt or by Houdini in the process of displaying, but they are obviously different. 

And third, you haven't really told us anything about what color space the original images are in, the ones you are loading and trying to display. So it's hard to know what the right sequence of transforms should be to show you the "right" image.

**Comment by meshula** [comment]
Further to what Larry said, your image may in fact be correct, and it certainly looks like you are on the right track. To my eye, the Houdini view has allowed over unity colors to saturate, and your transform has remapped the over unity colors more conservatively into the displayable gamut. Again, as Larry mentioned, you are in the realm of tone mapping, which I'm sorry to say has not got a scientifically-canonical definition, it's very much in the realm of art and subjectivity. 

I have forked a project by tizian here - https://github.com/meshula/tonemapper - which might be helpful to you. You can experiment with many different tone mappers, and pick the one that gives you the results most similar to the look you are aiming for.

**Comment by klydeid** [comment]
Thanks guys.
it is very helpful.
i will check it.!

**Comment by kdt3rd** [comment]
Closing as not an EXR issue
