### ISSUE TITLE
Installation doc references CMAKE_SYSTEM_PREFIX, but CMake doesn't

### ISSUE THREAD

**Issue by JGoldstone** [AcademySoftwareFoundation/openexr#1197]
This is on the tip of master, 3e7d5ac8 as of this writing. macOS 11.6.1, cmake 3.21.4.

I see this warning, invoking cmake:

CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_SYSTEM_PREFIX

My -DCMAKE_SYSTEM_PREFIX=<blahblahblah> though came from the explicit advice in the section 'Sub-Libraries' in INSTALL.md.

That said, even though it didn't use CMAKE_SYSTEM_PREFIX, it did find the copy of Imath that I had built inside a pyenv version tree after I specified -DCMAKE_INSTALL_PREFIX=`pyenv prefix`, so, points to the team for that.

**Comment by meshula** [comment]
Good catch. The documentation should say CMAKE_SYSTEM_PREFIX_PATH, which is the name of the variable find_package uses in searching. CMAKE_SYSTEM_PREFIX doesn't mean anything. CMAKE_INSTALL_PREFIX on the other hand does not have _PATH suffix! Cmake is nothing if not consistently inconsistent. I think this why everyone kind of hates cmake!

**Comment by cary-ilm** [comment]
Good catch indeed, and the INSTALL.md instructions were rather out of date. I just submitted #1206 that hopefully improves things.

**Comment by cary-ilm** [comment]
And I believe CMAKE_PREFIX_PATH is the proper setting, not CMAKE_SYSTEM_PREFIX_PATH, so that's what the instructions say. If anyone wants to suggest a better policy, speak up.

**Comment by JGoldstone** [comment]
Hello Cary—

Indeed, CMAKE_PREFIX_PATH made it trivial for me to install OpenEXR in an environment set up by pyenv <https://github.com/pyenv/pyenv>:

> cmake -DCMAKE_PREFIX_PATH=`pyenv prefix` -DCMAKE_INSTALL_PREFIX=`pyenv prefix` /usr/local/repos/git/aswf/OpenEXR


Now, that said, prior to getting OpenEXR to adopt so easily to the environment set up by pyenv, I found myself thinking of baby harp seals as I had had to use absolutely every brutal trick I could think of to get Imath to similarly look to the same Python version, library dir, site-packages dir, Boost and boost python installation, etc:

> export pvk=3.10  # python version kludge

> cmake /usr/local/repos/git/aswf/Imath --debug-output -DPYTHON=ON -DPython_EXECUTABLE=`pyenv which python` -DPython_LIBRARY=`pyenv prefix`/lib/libpython${pvk}.dylib -DPython_INCLUDE_DIR=`pyenv prefix`/include/python${pvk} -DPython3_EXECUTABLE=`pyenv which python` -DPython3_LIBRARY=`pyenv prefix`/lib/libpython${pvk}.dylib -DPython3_INCLUDE_DIR=`pyenv prefix`/include/python${pvk} -DCMAKE_INSTALL_PREFIX=`pyenv prefix` -DPYIMATH_OVERRIDE_PYTHON_INSTALL_DIR=`pyenv prefix`/lib/python${pvk}/site-packages -DBOOST_ROOT=`pyenv prefix` -DBOOST_LIBRARYDIR=`pyenv prefix`/lib -DBOOST_INCLUDEDIR=`pyenv prefix`/include -DBoost_NO_SYSTEM_PATHS=ON



Would that Imath was as adaptable to being installed, in a self-contained way, into the Python installation that pyenv sets up…

For the record, OCIO was almost as easy as OpenEXR; alll I had to add was -DPython_EXECUTABLE and it went from there:

> cmake -DPython_EXECUTABLE=`pyenv which python` -DCMAKE_PREFIX_PATH=`pyenv prefix` -DCMAKE_INSTALL_PREFIX=`pyenv prefix` /usr/local/repos/git/aswf/OpenColorIO


OpenImageIO was somewhere in between:

> cmake -DBoost_NO_SYSTEM_PATHS=ON -DCMAKE_PREFIX_PATH=`pyenv prefix` -DBoost_ROOT=`pyenv prefix` -DBOOST_INCLUDEDIR=`pyenv prefix`/include -DBOOST_LIBRARYDIR=`pyenv prefix`/lib -DPython_EXECUTABLE=`pyenv which python` -DCMAKE_INSTALL_PREFIX=`pyenv prefix` /usr/local/repos/git/openimageio


If you could make Imath as easy to install (into a pyenv-set-up Python installation) that would make my life easier. pyenv has install hooks, and it would be great to be able to know that just by saying ‘pyenv install 3.10.1’, say, that I would get something preloaded with Boost Python, Imath, OpenEXR, OpenColorIO and OpenImageIO.

Best—
—Joseph

ps: if you believe that Imath should already adapt completely and gracefully with just a specification of CMAKE_PREFIX_PATH, I would be happy to file an issue.

**Comment by meshula** [comment]
The difference between the two is:

`CMAKE_SYSTEM_PREFIX_PATH` - search includes system wide install locations.

https://cmake.org/cmake/help/latest/variable/CMAKE_SYSTEM_PREFIX_PATH.html

example: My project includes OpenEXR. We have a site-wide installation at /stdio/local that has Imath in it and all our other dependencies that should be shared, so I added /studio/local, because I want it to be considered in addition to /usr/local

----------

`CMAKE_PREFIX_PATH` - searches to be set by a project itself for its own searches

https://cmake.org/cmake/help/latest/variable/CMAKE_PREFIX_PATH.html

example: My project includes OpenEXR. I know where Imath is, I built it to a specific place, so I added it to CMAKE_PREFIX_PATH before I included OpenEXR.

Hope this helps!

**Comment by JGoldstone** [comment]
Right. I shouldn’t have put them into the email in the order that I did. Obviously I was building Imath before OpenEXR (but after Boost). Here’s a transcript of my build process, starting with installation of a blank pyenv Python (in this case, 3.8.11):

Last login: Fri Nov 19 16:23:01 on ttys001
 1001 % export PYTHON_CONFIGURE_OPTS="--enable-framework"
 1002 % pyenv install 3.8.11
Downloading openssl-1.1.1k.tar.gz...
-> https://www.openssl.org/source/openssl-1.1.1k.tar.gz
Installing openssl-1.1.1k...
Installed openssl-1.1.1k to /usr/local/repos/git/pyenv/versions/3.8.11

Downloading readline-8.1.tar.gz...
-> https://ftpmirror.gnu.org/readline/readline-8.1.tar.gz
Installing readline-8.1...
Installed readline-8.1 to /usr/local/repos/git/pyenv/versions/3.8.11

Downloading Python-3.8.11.tar.xz...
-> https://www.python.org/ftp/python/3.8.11/Python-3.8.11.tar.xz
Installing Python-3.8.11...
python-build: use zlib from xcode sdk
Installed Python-3.8.11 to /usr/local/repos/git/pyenv/versions/3.8.11

 1003 % pyenv shell 3.8.11
 1004 % `pyenv which python` -m pip install --upgrade pip
Requirement already satisfied: pip in /usr/local/repos/git/pyenv/versions/3.8.11/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (21.1.1)
Collecting pip
  Using cached pip-21.3.1-py3-none-any.whl (1.7 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 21.1.1
    Uninstalling pip-21.1.1:
      Successfully uninstalled pip-21.1.1
Successfully installed pip-21.3.1
 1005 % `pyenv which python` -m pip install --upgrade setuptools
Requirement already satisfied: setuptools in /usr/local/repos/git/pyenv/versions/3.8.11/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (56.0.0)
Collecting setuptools
  Downloading setuptools-59.2.0-py3-none-any.whl (952 kB)
     |████████████████████████████████| 952 kB 5.9 MB/s            
Installing collected packages: setuptools
  Attempting uninstall: setuptools
    Found existing installation: setuptools 56.0.0
    Uninstalling setuptools-56.0.0:
      Successfully uninstalled setuptools-56.0.0
Successfully installed setuptools-59.2.0
 1006 % `pyenv which python` -m pip install numpy
Collecting numpy
  Using cached numpy-1.21.4-cp38-cp38-macosx_10_9_x86_64.whl (16.9 MB)
Installing collected packages: numpy
Successfully installed numpy-1.21.4
 1007 % pip list
Package    Version
---------- -------
numpy      1.21.4
pip        21.3.1
setuptools 59.2.0
 1008 % mkdir -p /tmp/build/boost
 1009 % cd /tmp/build/boost
 1010 % (cd /usr/local/src/boost; tar cBf -) | tar xBf -
tar: no files or directories specified
 1011 % (cd /usr/local/src/boost; tar cBf - *) | tar xBf -
 1012 % ./bootstrap.sh --with-python=`pyenv which python` --prefix=`pyenv prefix` --with-libraries=python,thread,system,filesystem
zsh: no such file or directory: ./bootstrap.sh
(returned status 127) 1013 % pushd boost_1_77_0
 1014 % ./bootstrap.sh --with-python=`pyenv which python` --prefix=`pyenv prefix` --with-libraries=python,thread,system,filesystem
Building B2 engine..

###
###
### Using 'clang' toolset.
###
###

Apple clang version 13.0.0 (clang-1300.0.29.3)
Target: x86_64-apple-darwin20.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

###
###

> clang++ -x c++ -std=c++11 -O3 -s -DNDEBUG builtins.cpp class.cpp command.cpp compile.cpp constants.cpp cwd.cpp debug.cpp debugger.cpp execcmd.cpp execnt.cpp execunix.cpp filesys.cpp filent.cpp fileunix.cpp frames.cpp function.cpp glob.cpp hash.cpp hcache.cpp hdrmacro.cpp headers.cpp jam_strings.cpp jam.cpp jamgram.cpp lists.cpp make.cpp make1.cpp md5.cpp mem.cpp modules.cpp native.cpp object.cpp option.cpp output.cpp parse.cpp pathnt.cpp pathsys.cpp pathunix.cpp regexp.cpp rules.cpp scan.cpp search.cpp startup.cpp subst.cpp sysinfo.cpp timestamp.cpp variable.cpp w32_getreg.cpp modules/order.cpp modules/path.cpp modules/property-set.cpp modules/regex.cpp modules/sequence.cpp modules/set.cpp -o b2
Sld: warning: option -s is obsolete and being ignored
> cp b2 bjam
tools/build/src/engine/b2
Detecting Python version... 3.8
Detecting Python root... /usr/local/repos/git/pyenv/versions/3.8.11/Library/Frameworks/Python.framework/Versions/3.8
Unicode/ICU support for Boost.Regex?... /opt/local
Generating B2 configuration in project-config.jam for clang...

Bootstrapping is done. To build, run:

    ./b2
    
To generate header files, run:

    ./b2 headers

The configuration generated uses clang to build by default. If that is
unintended either use the --with-toolset option or adjust configuration, by
editing 'project-config.jam'.

Further information:

   - Command line help:
     ./b2 --help
     
   - Getting started guide: 
     http://www.boost.org/more/getting_started/unix-variants.html
     
   - B2 documentation:
     http://www.boost.org/build/

 1015 % ./b2 install
Performing configuration checks

    - default address-model    : 64-bit [1]
    - default architecture     : x86 [1]
    - has std::atomic_ref      : no [2]
    - has statx                : no [2]
    - has statx syscall        : no [2]
    - has init_priority attribute : yes [2]
    - has stat::st_blksize     : no [2]
    - has stat::st_mtim        : no [2]
    - has stat::st_mtimensec   : no [2]
    - has stat::st_mtimespec   : yes [2]
    - has stat::st_birthtim    : no [2]
    - has stat::st_birthtimensec : no [2]
    - has stat::st_birthtimespec : yes [2]
    - compiler supports SSE2   : yes [2]
    - compiler supports SSE4.1 : yes [2]
    - lockfree boost::atomic_flag : yes [2]
    - has std::atomic_ref      : no [3]
    - has statx                : no [3]
    - has statx syscall        : no [3]
    - has init_priority attribute : yes [3]
    - has stat::st_blksize     : no [3]
    - has stat::st_mtim        : no [3]
    - has stat::st_mtimensec   : no [3]
    - has stat::st_mtimespec   : yes [3]
    - has stat::st_birthtim    : no [3]
    - has stat::st_birthtimensec : no [3]
    - has stat::st_birthtimespec : yes [3]
    - compiler supports SSE2   : yes [3]
    - compiler supports SSE4.1 : yes [3]
    - lockfree boost::atomic_flag : yes [3]

[1] clang-13
[2] clang-darwin-13/release/python-3.8/threadapi-pthread/threading-multi/visibility-hidden
[3] clang-darwin-13/release/link-static/python-3.8/threadapi-pthread/threading-multi/visibility-hidden

Component configuration:

    - atomic                   : not building
    - chrono                   : not building
    - container                : not building
    - context                  : not building
    - contract                 : not building
    - coroutine                : not building
    - date_time                : not building
    - exception                : not building
    - fiber                    : not building
    - filesystem               : building
    - graph                    : not building
    - graph_parallel           : not building
    - headers                  : not building
    - iostreams                : not building
    - json                     : not building
    - locale                   : not building
    - log                      : not building
    - math                     : not building
    - mpi                      : not building
    - nowide                   : not building
    - program_options          : not building
    - python                   : building
    - random                   : not building
    - regex                    : not building
    - serialization            : not building
    - stacktrace               : not building
    - system                   : building
    - test                     : not building
    - thread                   : building
    - timer                    : not building
    - type_erasure             : not building
    - wave                     : not building

...patience...

[tons of predictable boost output elided]

...updated 16385 targets...
 1016 % mkdir ../../imath
 1017 % cd ../../imath

[here I forgot to specify -DPYTHON=ON…]

 1018 % cmake -DCMAKE_PREFIX_PATH=`pyenv prefix` -DCMAKE_INSTALL_PREFIX=`pyenv prefix` /usr/local/repos/git/aswf/Imath
-- The C compiler identification is AppleClang 13.0.0.13000029
-- The CXX compiler identification is AppleClang 13.0.0.13000029
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Setting build type to 'Release' as none was specified.
-- Configure Imath 3.2.0-dev, library API version: 29.0.0
-- Looking for sin in m
-- Looking for sin in m - found
-- clang-format not found.
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/build/imath

[Inspected CMakeCache.txt, realized I’d forgotten -DPYTHON=ON, wiped out what’s in the dir and restarted…]

 1019 % emacs CMakeCache.txt
 1020 % rm -fr *
zsh: sure you want to delete all 10 files in /tmp/build/imath [yn]? y
 1021 % cmake -DCMAKE_PREFIX_PATH=`pyenv prefix` -DCMAKE_INSTALL_PREFIX=`pyenv prefix` -DPYTHON=ON /usr/local/repos/git/aswf/Imath
-- The C compiler identification is AppleClang 13.0.0.13000029
-- The CXX compiler identification is AppleClang 13.0.0.13000029
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Setting build type to 'Release' as none was specified.
-- Configure Imath 3.2.0-dev, library API version: 29.0.0
-- Looking for sin in m
-- Looking for sin in m - found
-- Found Python: /usr/local/repos/git/pyenv/shims/python3.9 (found version "3.9.9") found components: Interpreter Development Development.Module Development.Embed 
-- Found Python3: /usr/local/repos/git/pyenv/shims/python3.9 (found version "3.9.9") found components: Interpreter Development Development.Module Development.Embed 
-- Found Python 3.9.9
-- Found Python3 libraries: 39
-- Will install to: /Users/jgoldstone/Library/Python/3.9/lib/python3.9/site-packages
-- Disabling boost-provided cmake config. If this causes problems, consider setting Boost_NO_BOOST_CMAKE variable to OFF
-- Found Boost: /usr/local/repos/git/pyenv/versions/3.8.11/include (found version "1.77.0") found components: python python3 python39 
-- Found Python 3 boost: Boost::python39
-- Found NumPy 1.21.4 for Python 3.9.9: /opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/numpy/core/include
-- clang-format not found.
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/build/imath
 1022 %

Note how
it picks up Python 3.9.9, which is in /opt/local/bin.
Similarly it picks up numpy from /opt/local/Library/Frameworks/Python.framework/Versions/3.9/ilb/python3.9/site-packages/numpy/core/include
It’s going to install to ~/Library/Python/3.9/lib/python3.9/site-packages; at the moment, ~/Library/Python/3.9 doesn’t even exist.
It claims to have found 3.9 in /usr/local/repos/git/pyenv/
There is no 3.9.9 installed via pyenv:

 1029 % pyenv versions
  system
  3.10.0
  3.8.10
* 3.8.11 (set by PYENV_VERSION environment variable)
  3.8.12
  3.9.7
 1030 %

Pyenv shims are, as to be expected, at the head of PATH:

/usr/local/repos/git/pyenv/shims:/usr/local/repos/git/pyenv/bin:/Users/jgoldstone/bin:/Users/jgoldstone/.poetry/bin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/Library/TeX/texbin:/opt/X11/bin:/Library/Apple/usr/bin:/Applications/Wireshark.app/Contents/MacOS
 1034 %   

So, Nick, were you expecting that it would suffice to set CMAKE_PREFIX_PATH to the 3.8.11 pyenv installation, and everything would just fall into place, localized to it?

If that’s what it’s supposed to do, then I suppose I should file an issue on it. In which case, if we are debugging CMAKE issues, what diagnostic information can I provide with the filing?

Best—
—joseph

**Comment by cary-ilm** [comment]
Closing, this was addressed by #1206.
