### ISSUE TITLE
Openexr on vcpkg is ooooooold.

### ISSUE THREAD

**Issue by crazydef** [AcademySoftwareFoundation/openexr#1207]
I'm trying to use a third party library that depends on openexr.  Their build instructions recommend using vcpkg to fetch dependencies, however the version of openexr available through vcpkg is only 2.5.0#3.

Is there anyway that can be updated?

(The actual issue is incompatibilities in imath.  Version 3.1.3 of that is available through vcpkg so some libraries are using that, while openexr is trying to explicitly use imath 2.5.)

**Comment by meshula** [comment]
Thanks for noting that. I've opened an issue at vcpkg, as it doesn't seem like they're aware of the problem yet.

**Comment by EvanAW** [comment]
This can be closed since https://github.com/microsoft/vcpkg/pull/26862 has landed.

**Comment by meshula** [comment]
It has indeed!! Thanks for noting that.
