### ISSUE TITLE
Windows min/max build test failure

### ISSUE THREAD

**Issue by Arbeyem** [AcademySoftwareFoundation/openexr#1215]
Using openexr v3.1.3.
'src/test/openexrcoretest/compression.cpp' throws multiple min/max is not a member of 'std' errors when compiling.

What I tried:
Ensured NOMINMAX was properly defined, no change.  Including \<algorithm\> in the file resolved the issue.

What happened:
Build fails when the CMake option 'BUILD_TESTING' is set to 'ON' (default) on Windows using MSVC14.

What you expected to happen instead:
Test compiles successfully.

**Comment by meshula** [comment]
Thanks for the report. Please feel free to submit a PR, or we can take care of it.

**Comment by cary-ilm** [comment]
Apologies for missing this. PR #1238 adds <algorithm>. Presumably this is peculiar to MSVC14, since it works with 16 and 17 in our CI.
