### ISSUE TITLE
Can I link this to Python3.7 and import successfully? 

### ISSUE THREAD

**Issue by Erisnoit** [AcademySoftwareFoundation/openexr#1233]
I want to install and import openexr into Python3.7,
but get big difficult when installing it.

FIRST, I use 'pip install openexr' and have some error which i couldn't find the right solution.
errors as follows:
![image](https://user-images.githubusercontent.com/89090767/154450376-703d3283-4779-4b2c-8033-3a60bb563bf9.png)
![image](https://user-images.githubusercontent.com/89090767/154450587-97e1ad5c-afa6-418d-8d0f-9175570992e2.png)
![image](https://user-images.githubusercontent.com/89090767/154450641-f3389931-259c-4121-b456-560af3692638.png)
I don't really know what's wrong when using pip, according to picture it seems not the problem from pip.  And pip version is 22.0.3.

THEN, I check the web and find this source and try to install from this. I make and install it successfully, but it seems not work in python, or not link to Python?Is there any way can solve this and make it work? 

Thanks a lot, if any question above you could help.

**Comment by peterhillman** [comment]
As mentioned in the [FAQ](https://github.com/AcademySoftwareFoundation/openexr#frequently-asked-questions), the openexr python module isn't part of this project. It does not support recent OpenEXR versions, so [OpenImageIO](https://sites.google.com/site/openimageio/home) might be a better choice for reading and writing OpenEXR images from python code.
