### ISSUE TITLE
[RB-2.5] exec_prefix for PyIlmBase

### ISSUE THREAD

**Issue by waebbl** [AcademySoftwareFoundation/openexr#1252]
While packaging OpenEXR 2.5.8 for Gentoo, I noticed, the exec_prefix for the pkgconfig file of PyIlmBase is wrong. According to GNU standards[1], it should usually be `${prefix}`, which IMO implies it needs to be an absolute path. The current pkgconfig file for PyIlmBase lists `exec_prefix=bin`.

[1] https://www.gnu.org/prep/standards/html_node/Directory-Variables.html

**Comment by cary-ilm** [comment]
Clean up loose ends, this should be closed now.
