### ISSUE TITLE
use exrheader to determine the precision of exr file

### ISSUE THREAD

**Issue by funnyvalentine2363** [AcademySoftwareFoundation/openexr#1275]
Hi, i've been working on 32bit and 16bit exr images recently.
there are some images that gimp show to be 16bit, but later turns out to be np.float32 when i use opencv and oiio read them.
if i use exrheader read the image, its 16bit. now i'm totally confused because oiio was built based on openexr.
could anyone please tell me which one is the ultimate way to determine whether an exr file is 16bit or 32bit?

**Comment by lgritz** [comment]
Do you have an example file you can share?

I can't think of any reason why exrheader and OIIO would give different answers, though I wonder if maybe it was a file of *mixed* half and float channels. In that case, the answer is not "is it 16 or 32 bit" but "it is both", and the reporting of the various programs may need more subtle interpretation. For OIIO, there is one field "format" that gives a single data type that has enough precision to hold any of the channels, and a separate "channelformats" vector that, only for mixed-type files, will give you the individual type for each channel.

**Comment by funnyvalentine2363** [comment]
[dis_height_1_4.exr.zip](https://github.com/AcademySoftwareFoundation/openexr/files/9485979/dis_height_1_4.exr.zip)
this image has only one channel so i think it's not mixed precision kind of thing.
code i used to read the image
oiio:
> import OpenImageIO as oiio
> import numpy as np
> img = oiio.ImageInput.open('dis_height_1_4.exr')
> a = img.read_image("float")
> print(a.dtype)
> print(a[a!=0.5])

which yields
> float32
> [0.5288086 0.5288086 0.5288086 ... 0.5332031 0.5332031 0.5332031]

opencv:

> import os
> os.environ["OPENCV_IO_ENABLE_OPENEXR"]="1"
> import cv2
> img = cv2.imread('dis_height_1_4.exr',-1)

which yields the same result

exrheader:

./exrheader  dis_height_1_4.exr

> channels: 16-bit floating-point,sampling 1 1

**Comment by lgritz** [comment]
The example is very helpful.

    $ oiiotool -info dis_height_1_4.exr
    dis_height_1_4.exr   : 8192 x 8192, 1 channel, half openexr

OIIO correctly reports that it's "half", which is 16 bit float, same as reported by exrheader.

In your python code,

    a = img.read_image("float")
    print(a.dtype)

In the first line, you are <ahem> specifically asking it to convert the data to float for the numpy array it returns. And then in the second line, you are having it print the type of the numpy array, which is float, exactly as you asked for it to be.

**Comment by funnyvalentine2363** [comment]
> The example is very helpful.
> 
> ```
> $ oiiotool -info dis_height_1_4.exr
> dis_height_1_4.exr   : 8192 x 8192, 1 channel, half openexr
> ```
> 
> OIIO correctly reports that it's "half", which is 16 bit float, same as reported by exrheader.
> 
> In your python code,
> 
> ```
> a = img.read_image("float")
> print(a.dtype)
> ```
> 
> In the first line, you are specifically asking it to convert the data to float for the numpy array it returns. And then in the second line, you are having it print the type of the numpy array, which is float, exactly as you asked for it to be.

So the original image only consists of 16 bit, the reason i could show float32 and 0.5288086 is merely because i manually convert them to float32 (so that numpy could show more numbers)? That's really helpful, thanks. Have a good day.
