### ISSUE TITLE
FIX for 2.2.0 buglet in two Makefile.am preventing OpenEXR upgrade with older version installed

### ISSUE THREAD

**Issue by mandree** [AcademySoftwareFoundation/openexr#130]
I have been porting the ilmbase and OpenEXR 2.2.0 packages for FreeBSD and came across one issue with OpenEXR, and that is include file ordering.

If I
1. have OpenEXR and ilmbase 2.1.0 installed, 
2. upgrade ilmbase to 2.2.0, and 
3. then attempt to build OpenEXR 2.2.0, 

it will fail because the OpenEXR 2.2.0 grabs the OpenEXR 2.1.0's header files from the system include directory.

The obvious workaround is "deinstall OpenEXR 2.1.0 before attempting to build 2.2.0", but that subverts all our automation and I believe is a general issue worth fixing.

The culprit apparently is the INCLUDES = statement in the IlmImf/Makefile.am and IlmImfUtil/Makefile.am, these have code similar to, respectively:

``` makefile
INCLUDES = @ILMBASE_CXXFLAGS@ \
           -I$(top_builddir)  \
           -I$(top_srcdir)/config
```

or

``` makefile
INCLUDES = @ILMBASE_CXXFLAGS@ \
           -I$(top_builddir)  \
           -I$(top_srcdir)/IlmImf  \
           -I$(top_srcdir)/config
```

Now, on my system ilmbase and OpenEXR share the include path, and both stuff their includes into /usr/local/include/OpenEXR/. This is reflected in `@ILMBASE_CXXFLAGS@`.

This also means that the OpenEXR 2.2 build will grab the older 2.1 installed include files.

The fix is simple, move the `@ILMBASE_CXXFLAGS@` after the local `-I$(top_whichever)` options, such as (only for IlmImfUtil/Makefile.am):

``` makefile
INCLUDES = -I$(top_builddir)  \
           -I$(top_srcdir)/IlmImf  \
           -I$(top_srcdir)/config \
       @ILMBASE_CXXFLAGS@
```

Then the local includes will get preference, and the system includes will only fill in the missing pieces (i. e. ilmbase stuff where required).

Please consider making such changes before the next release.

**Comment by cary-ilm** [comment]
Looking into the backlog of open OpenEXR issues. This should be resolved with the improvements to cmake.  Closing the issue for now, feel free to re-open or file a new issue if you need further help.
