### ISSUE TITLE
Update CII test_continuous_integration_justification for GHA

### ISSUE THREAD

**Issue by jfpanisset** [AcademySoftwareFoundation/openexr#1318]
Under the Gold / Quality section of the CII badge:

https://bestpractices.coreinfrastructure.org/en/projects/2799?criteria_level=2#quality

the justification mentioning Azure Pipelines should be updated to GitHub Actions. It currently says:

> Continuous integration via Azure pipelines: https://dev.azure.com/openexr/. Builds are triggered on each PR.

**Comment by cary-ilm** [comment]
Fixed, thanks for the catch.
