### ISSUE TITLE
Link openexr.com

### ISSUE THREAD

**Issue by mond-cz** [AcademySoftwareFoundation/openexr#1320]
**About** text is ending by link to web page [http://www.openexr.com/](http://www.openexr.com/) that runs over _.org_ back to GitHub page ...

**Comment by cary-ilm** [comment]
We're in the process of replacing the old website, this is a work in progress, and we will hopefully roll out a new website in the next few weeks.

**Comment by vvzen** [comment]
Hello!

Has the new website been rolled out successfully ?

In my team docs, I had a link pointing to the https://www.openexr.com/documentation/TechnicalIntroduction.pdf PDF , but now I get a 404 after a redirection to https://github.com/AcademySoftwareFoundation/openexr/documentation/TechnicalIntroduction.pdf .
Is this in the works?
Thanks!

**Comment by meshula** [comment]
The Technical Introduction is now here: https://openexr.readthedocs.io/en/latest/TechnicalIntroduction.html

The files that didn't make it over to readthedocs are

https://web.archive.org/web/20130508232717/http://www.openexr.com/UsingOpenEXRandCTL.pdf
https://web.archive.org/web/20130508232717/http://www.openexr.com/OpenEXRColorManagement.pdf

and

https://web.archive.org/web/20130508232717/http://www.openexr.com/OpenEXRViewers.pdf
https://web.archive.org/web/20130508232717/http://www.openexr.com/photoshop_plugin.html

The two documents about color management are of historical interest, I refer to them frequently. I think we ought to host them as well.

**Comment by cary-ilm** [comment]
The website is still in the works, hopefully resolved soon, apologies for the churn.  The "Technical Introduction" content is and will continue to be under here: https://openexr.readthedocs.io.  The exact document with the content of the original .pdf is currently [here](https://openexr.readthedocs.io/en/latest/TechnicalIntroduction.html), although that location may move. Ultimately, the https://openexr.com site will link to that.

**Comment by cary-ilm** [comment]
The https://openexr.com website should be in order now. All the documentation should be in its logical place, but if anything is amiss or confusing or missing, please let us know.
