### ISSUE TITLE
openexr 3.1.6 regression: does not compile on ARM v7 due to unguarded use of unavailable AARCH64 intrinsics

### ISSUE THREAD

**Issue by mandree** [AcademySoftwareFoundation/openexr#1365]
@aras-p Pull Request #1348 and commit https://github.com/AcademySoftwareFoundation/openexr/commit/677c6a52d8cde3b8630932a93b631d2d4e68ab52 seem to introduce breaking changes on ARMv7, see https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=270348 

The code assumes that if ARM NEON extensions are available, it can use `vqtbl1q_u8`, `vzip1q_u8` and `vzip2q_8`.
From the little I understand from browsing ARM NEON arch' manuals, this intrinsic appears to only be available on AArch64 but not 32-bit ARMv7.

If that is true: Can we please have guards around the Aarch64 stuff?
If I am misunderstanding, what do you need or suggest to solve this?

**Comment by cary-ilm** [comment]
Is this fixed by #1358? If not, better guards are in order.

**Comment by mandree** [comment]
@cary-ilm I don't have ARMv7 around, I am relaying a report from a FreeBSD fellow; reading #1358 it looks as though the detection would be helpful, but since that emulates only vst1q... but not vqtbl1q... I don't see how it could possibly help.
Furthermore, this does not appear to be a missing feature of the compiler or header file, but actual unavailability of the ARMv8 Aarch64 NEON instruction on ARMv7 hardware. (I have looked at LLVM/clang 10.0 and 4.0 headers which would define this if on `__ARM_NEON` and `__aarch64__`. FreeBSD uses LLVM for its cc/c++.)

**Comment by cary-ilm** [comment]
@mandree I don't have an ARM device to test with either, relying on others to do the leg-work. @aras-p, what solution to you recommend? The substitute intrinsic that @betajippity provided in #1358 looks close but there's more missing, right? Thanks for any help in getting this sorted out.

**Comment by mandree** [comment]
My take is that some #ifdef/#define work would be in order that sets ILM_HAVE_NEON_AARCH64 or similar, and makes the vzip and vqtbl stuff depend on that rather than just ILM_HAVE_NEON. If done as bluntly as suggested here, that would make the optimization unavailable on ARMv7.

I have sketched this proposal in two attachments to https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=270348 - but unless there are newer comments in that bug report, these are untested, so I do not know if they are doing the right thing.

**Comment by aras-p** [comment]
Ah I did not realize that anyone would build OpenEXR on armv7. My bad, sorry! I think I'd go for just not using the NEON code path there (i.e. only enable it on armv8/aarch64); that way it stays the same as it was before #1348. I'll try to submit a fix today.

**Comment by clausecker** [comment]
@aras-p OpenEXR appears as a transitive dependency in some desktop software.  E.g. ImageMagick and windowmaker depend on it.
