### ISSUE TITLE
CI: set minimal permissions on GitHub Workflows

### ISSUE THREAD

**Issue by diogoteles08** [AcademySoftwareFoundation/openexr#1413]
Hi!

I see that your workflows don't specify the permissions for its jobs, so their privileges are being determined by GitHub's defaults. If you define minimal permissions you would be secured against erroneous or malicious actions from external jobs you call from your workflow. It's specially important for the case they get compromised, for example.

The ideal would be to set a top-level read-only permission on all workflows, so that they would be inherited by any job that does not define job-level permissions. It seems that currently none of your workflows require any write permissions -- but in case you need them in the future, you can keep the top-level read-only permissions and add the required new permissions as job-level.

Setting minimum permissions for workflows is recommended by [GitHub itself](https://docs.github.com/en/actions/security-guides/automatic-token-authentication) and also by other security tools, such as [Scorecards](https://github.com/ossf/scorecard) and [StepSecurity](https://github.com/step-security).

Let me know what you think about this. If you agree, I'd be happy to raise a PR with the changes.

#### Context
I'm Diogo and I work on Google's Open Source Security Team([GOSST](https://github.com/diogoteles08#about-gosst-ghost)) in cooperation with the Open Source Security Foundation ([OpenSSF](https://openssf.org/)). My core job is to suggest and implement security changes on widely used open source projects 😊

**Comment by cary-ilm** [comment]
Sounds good, and yes, please submit a PR, happy to have the contribution. Thanks!

**Comment by diogoteles08** [comment]
Great! I'll be raising a PR shortly
