### ISSUE TITLE
-DOPENEXR_ENABLE_THREADING=OFF does not seems to work on Windows and MacOS

### ISSUE THREAD

**Issue by sanguinariojoe** [AcademySoftwareFoundation/openexr#1455]
I am using GitHub actions to build the Python wrapper for OpenEXR. Apparently threading is giving the users some problems, so i tried to disable it adding the -DOPENEXR_ENABLE_THREADING=OFF option.

Unfortunately, everything seems to work with Linux, but on Windows and MacOs it is failing:

https://github.com/sanguinariojoe/pip-openexr/actions/runs/5275522633/jobs/9541100520
https://github.com/sanguinariojoe/pip-openexr/actions/runs/5275642197/jobs/9541349829

In both cases it was trying to compile the sources into the src/lib/IlmThread/ folder, which I suppose is not the intended behavior

**Comment by meshula** [comment]
Thanks for the report, that needs a closer look.

**Comment by cary-ilm** [comment]
Hopefully fixed by #1462
