### ISSUE TITLE
Add VFX Platform 2023 to CI Build Matrix

### ISSUE THREAD

**Issue by jfpanisset** [AcademySoftwareFoundation/openexr#1458]
There is now a VFX Platform 2023 version of the ci-openexr aswfdocker build container available:

https://hub.docker.com/layers/aswf/ci-openexr/2023/images/sha256-90ffb0f029737b05200b76e2f0bcb3b0177bc7440e30b867ca02b6df38950327?context=explore

It could now be added to the CI build matrix:

https://github.com/AcademySoftwareFoundation/openexr/blob/e504fb2ec3952e5f4202c33e0baea21d8ea8f9e1/.github/workflows/ci_workflow.yml#L61

There has been a fair number of changes to these containers since VFX Platform 2022, feedback welcome if any issues crop up.

**Comment by cary-ilm** [comment]
Done #1475
