### ISSUE TITLE
implicit declaration of function 'vld1q_f32_x2'

### ISSUE THREAD

**Issue by dlemstra** [AcademySoftwareFoundation/openexr#1477]
My Linux arm64 cross-compilation no longer works with the latest code of this repository. This issue can be reproduced with the following `Dockerfile`:

```
FROM ubuntu:18.04

RUN apt-get update -y && \
    apt-get install -y autoconf clang-format git python3-pip \
    binutils-aarch64-linux-gnu gcc-aarch64-linux-gnu g++-aarch64-linux-gnu

RUN pip3 install --upgrade pip && \
    pip3 install cmake==3.24.1.1

ENV CC=aarch64-linux-gnu-gcc
ENV CXX=aarch64-linux-gnu-g++

RUN printf 'set(CMAKE_SYSTEM_NAME Linux)\n\
set(CMAKE_SYSTEM_PROCESSOR aarch64)\n\
set(CMAKE_CROSSCOMPILING TRUE)\n\
' > /cross-compilation.cmake

RUN git clone https://github.com/AcademySoftwareFoundation/openexr.git && \
    cd openexr && \
    cmake -DBUILD_SHARED_LIBS=off -DCMAKE_TOOLCHAIN_FILE=/cross-compilation.cmake . && \
    make
```

This issue can be resolved by adding the same check as in `ImfSimd.h`:

```c
#include "OpenEXRConfigInternal.h"
#ifdef OPENEXR_MISSING_ARM_VLD1
/* Workaround for missing vld1q_f32_x2 in older gcc versions.  */

__extension__ extern __inline float32x4x2_t
    __attribute__ ((__always_inline__, __gnu_inline__, __artificial__))
    vld1q_f32_x2 (const float32_t* __a)
{
    float32x4x2_t ret;
    asm ("ld1 {%S0.4s - %T0.4s}, [%1]" : "=w"(ret) : "r"(__a) :);
    return ret;
}
#endif
```

But I wonder if `ImfSimd.h` should be shared between `OpenEXR` and `OpenEXRCore` to make sure the simd defines and workarounds are the same in both folders?

**Comment by meshula** [comment]
That makes sense. My preference would be that this simd code be canonically in OpenEXRCore, and that ImfSimd.h share the Core one. We're working towards Core being usable without its needing to peek outside for code and headers.

**Comment by cary-ilm** [comment]
#1482 hopefully gets things cross-compiling again. Consider this a temporary fix until we can do a more thoughtful consolidation of the compiler/system checks between OpenEXR and OpenEXRCore.

**Comment by cary-ilm** [comment]
Closing, I believe this has been resolved, but feel free to reopen if something is still amiss.
