### ISSUE TITLE
dll's for Windows

### ISSUE THREAD

**Issue by Gavin-Williams** [AcademySoftwareFoundation/openexr#1491]
Hi,

Where can I download the dlls?

I saw some nuget packages that were years out of date, are they released by you guys?

**Comment by meshula** [comment]
We don't maintain any distributions or downloads outside of this github repo; any others you encounter  are community run. The dlls in vcpkg are 3.1.8, perhaps that'll suit your needs?

**Comment by Gavin-Williams** [comment]
That sounds good to me. I live in a C# and tools-based world mostly, where everything I need is just a few button clicks away - I do not build libraries. Yesterday was the first time I ever used cmake, trying to build openexr and it didn't work. That's a warning sign to me. That kind of stuff often turns into a big waste of time.

So, are you saying Microsoft maintain builds as part of their vcpkg - I don't even know what that is. Remember I said I'm a C# guy. I'm the kind of guy that reads about C++ modules and hopes that he might never have to write a header file again ... YES! <fistpump>

I'll watch a video about vcpkg I guess. Is it a package installer, like nuget? I suppose I'll find out.

UPDATE:
* installed git
* installed vcpkg
* worked out how to download and build packages

And I can see openexr 3.1.8! Thanks for leading me in the right direction. I wouldn't have worked that out without your helpful comment! Thank you.

**Comment by meshula** [comment]
Glad that worked for you ~ feel free to comment here further if you've got questions.
