### ISSUE TITLE
Fix version in RB-3.2 branch

### ISSUE THREAD

**Issue by cary-ilm** [AcademySoftwareFoundation/openexr#1524]
The release version appears to be specified in two places, in `OpenEXRConfig.h.in` and in `openexr_version.h`, so as it stands, the version is correct in the current 3.2 release branch but for subsequent patch releases would need to updated in two locations, which is problematic. This needs to get sorted out prior to release.

Presumably, `OpenEXRConfig.h.in` should read the values from`openexr_version.h` (or the `CMakeLists.txt` should).

**Comment by meshula** [comment]
See the comment here ~ originally I had intended OpenEXRConfig.h to include openexr_version.h, but ran into a snarl: https://github.com/AcademySoftwareFoundation/openexr/pull/1386#discussion_r1177177286 

Things have been further sorted out subsequently, should be possible to get it right now.

**Comment by Vertexwahn** [comment]
Just for the records openexr/src/wrappers/python/setup.py also depends on the contents of `openexr_version.h`:

```
with open('src/lib/OpenEXRCore/openexr_version.h', 'r') as f:
    txt = f.read()
    for name in ('MAJOR', 'MINOR', 'PATCH'):
        version.append(re.search(
            f'VERSION_{name} ([0-9]*)', txt).group(0).split(' ')[-1])
```

**Comment by meshula** [comment]
A good supporting argument for `openexr_version.h` being the ground truth.

**Comment by kmilos** [comment]
> read the values from`openexr_version.h` (or the `CMakeLists.txt` should)

If still needed, see e.g.  libtiff again for CMake ideas that gives pretty much equivalent to the python above: https://gitlab.com/libtiff/libtiff/-/blob/69eef88fc0e446c35213471f7277ee86265e5871/CMakeLists.txt#L35-L46 and https://gitlab.com/libtiff/libtiff/-/blob/69eef88fc0e446c35213471f7277ee86265e5871/cmake/AutotoolsVersion.cmake

**Comment by meshula** [comment]
ah, I see it, thanks, we could emulate this.

```
FILE(STRINGS "${CMAKE_CURRENT_SOURCE_DIR}/configure.ac" configure REGEX "^LIBTIFF_.*=")
foreach(line ${configure})
    foreach(var LIBTIFF_MAJOR_VERSION LIBTIFF_MINOR_VERSION LIBTIFF_MICRO_VERSION LIBTIFF_ALPHA_VERSION
            LIBTIFF_CURRENT LIBTIFF_REVISION LIBTIFF_AGE)
        if(NOT ${var} AND line MATCHES "^${var}=(.*)")
            set(${var} "${CMAKE_MATCH_1}")
            break()
        endif()
    endforeach()
endforeach()
```

**Comment by cary-ilm** [comment]
This should be resolve by #1527.
