### ISSUE TITLE
Convert code-blocks to literalincludes in ReadingAndWritingImageFiles.rst

### ISSUE THREAD

**Issue by cary-ilm** [AcademySoftwareFoundation/openexr#1549]
The example code in [`website/ReadingAndWritingImageFiles.rst`](https://github.com/AcademySoftwareFoundation/openexr/blob/main/website/ReadingAndWritingImageFiles.rst) should be moved to individual files in [`website/src`](https://github.com/AcademySoftwareFoundation/openexr/blob/main/website/src) and included in the documentation files via `.. literalinclude::`, and also included in [`website/src/all.cpp`](https://github.com/AcademySoftwareFoundation/openexr/blob/main/website/src/all.cpp) so that it get built by CMake for testing and validation. See the other uses of `literalinclude` as examples.

This task requires some basic familiarity with [reStructuredText](https://docutils.sourceforge.io/rst.html) and [sphinx](https://www.sphinx-doc.org/en/master) but the concepts are easy to pick up from other examples. See [Building the Website](https://openexr.com/en/latest/install.html#building-the-website) for how to test the formatting.

**Comment by MeghaS94** [comment]
I'll take a look at this for dev days.

**Comment by MeghaS94** [comment]
Just a clarifying question on this - There's about 34 code-blocks left in ReadingAndWritingImageFiles.rst, does that mean I'll need to add 34 new cpp files?
whenever possible, would it make sense to put code in the same cpp file, and reference what gets included in the rst files  with the start-after and end-before directives?

**Comment by cary-ilm** [comment]
Whatever makes sense is fine, but start-after/end-after sounds like a good approach for the shorter code snippets sounds like a good approach!

**Comment by MeghaS94** [comment]
Leaving an update here - I've made most of the changes for this, I will submit a PR soon. Thanks for all the help, Cary!
