### ISSUE TITLE
Add tests for ImfCRgbaFile.cpp

### ISSUE THREAD

**Issue by cary-ilm** [AcademySoftwareFoundation/openexr#1552]
Add tests to the test suite for the functions in [src/lib/OpenEXR/ImfCRgbaFile.cpp](https://github.com/AcademySoftwareFoundation/openexr/blob/main/src/lib/OpenEXR/ImfCRgbaFile.cpp).

These functions are C wrappers around the C++ API, so tests can follow the pattern of the other basic file I/O routines.

The tests should go in [src/test/OpenEXRTest](https://github.com/AcademySoftwareFoundation/openexr/tree/main/src/test/OpenEXRTest) and follow the established pattern.

**Comment by MeghaS94** [comment]
I'm planning to work on this for dev days this week.

**Comment by cary-ilm** [comment]
Great! Ping this ticket or the slack channel if you have questions

**Comment by MeghaS94** [comment]
Two follow up questions :
1) Should the tests for this use  C style file handling, exercise the functions in `src/lib/OpenEXR/ImfCRgbaFile.h`, and follow what's being done in `src/test/OpenEXRTest/testRgba.cpp`?
2) Are there any existing examples of tests written for other C wrappers?

**Comment by cary-ilm** [comment]
I think so. I don't think there are any tests for this api, but I think testRgba.cpp should be a good model. But keep it simple for now. Just try to replicate the writeReadRGBA() function and skip the "Incomplete" and "Layer" stuff. 

The api here is a wrapper around the usual api that testRgba.cpp uses, so you'll need to replace the class objects with equivalent calls to functions in ImfCRgbaFile.h. So you can probably just duplicate testRgba.cpp, delete the "incomplete" and "layer" stuff, then rewrite the other calls. 

Thanks!
