### ISSUE TITLE
Add tests for Header attribute iterator methods

### ISSUE THREAD

**Issue by cary-ilm** [AcademySoftwareFoundation/openexr#1554]
Add tests to the test suite for the `Header` classes attribute iterator methods in [src/lib/OpenEXR/ImfHeader.h](https://github.com/AcademySoftwareFoundation/openexr/blob/main/src/lib/OpenEXR/ImfHeader.h).

The coverage report that identifies the uncovered lines is [here](https://sonarcloud.io/component_measures?metric=uncovered_lines&selected=AcademySoftwareFoundation_openexr%3Asrc%2Flib%2FOpenEXR%2FImfHeader.h&view=list&id=AcademySoftwareFoundation_openexr)

The tests should go in [src/test/OpenEXRTest](https://github.com/AcademySoftwareFoundation/openexr/tree/main/src/test/OpenEXRTest) and follow the established pattern.

**Comment by MrGlobby** [comment]
Hi @cary-ilm! I was planning to do this for the ASWF dev days, but I can't see anything in the linked coverage report that highlights uncovered lines in ImfHeader.h. I can see such highlighting in other files, so I'm not sure what I'm missing?

**Comment by cary-ilm** [comment]
@MrGlobby the SonarCloud coverage report is sort of finicky and often confusing. In this case, I think I meant to post a link to the [ImfHeader.cpp](https://sonarcloud.io/component_measures?metric=uncovered_lines&selected=AcademySoftwareFoundation_openexr%3Asrc%2Flib%2FOpenEXR%2FImfHeader.cpp&view=list&id=AcademySoftwareFoundation_openexr) file.  The non-const `begin()` and `end()` methods appear to not get invoked. 

The low-tech approach is to put a print statement in the functions, then execute the test suite to confirm the message doesn't appear, then add the call to the test suite, rerun it and confirm the message appears. Then remove the print statement.

Of course, feel free to browse the SonarCloud coverage report and add anything else you see uncovered, this one just looked pretty straightforward.

**Comment by MrGlobby** [comment]
I've made a pull request for this, hope I've done it correctly! https://github.com/AcademySoftwareFoundation/openexr/pull/1577

**Comment by cary-ilm** [comment]
done, thanks.
