### ISSUE TITLE
Better failure reports from bin test suite

### ISSUE THREAD

**Issue by cary-ilm** [AcademySoftwareFoundation/openexr#1558]
Currently, the [test suite](https://github.com/AcademySoftwareFoundation/openexr/tree/main/src/test/bin) for the tool programs terminates with an unhelpful assertion on the return code when a program fails, without reporting the reason for the failure.

The python code that invokes the programs should print the subprocess's stdout and stderr, so the output logs are more helpful.

**Comment by cdleu430** [comment]
I was planning on looking into this for ASWF Dev Days (October 12-13th)
