### ISSUE TITLE
Linker error while installing `opencv`: Undefined symbols for architecture arm64

### ISSUE THREAD

**Issue by kafka-tamura** [AcademySoftwareFoundation/openexr#1566]
```[ 26%] Linking CXX shared library ../../lib/libopencv_imgcodecs.dylib
Undefined symbols for architecture arm64:
  "Imf_3_2::Chromaticities::Chromaticities(Imath_2_5::Vec2<float> const&, Imath_2_5::Vec2<float> const&, Imath_2_5::Vec2<float> const&, Imath_2_5::Vec2<float> const&)", referenced from:
      cv::ExrDecoder::ExrDecoder() in grfmt_exr.cpp.o
  "Imf_3_2::Header::Header(int, int, float, Imath_2_5::Vec2<float> const&, float, Imf_3_2::LineOrder, Imf_3_2::Compression)", referenced from:
      cv::ExrEncoder::write(cv::Mat const&, std::__1::vector<int, std::__1::allocator<int>> const&) in grfmt_exr.cpp.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [lib/libopencv_imgcodecs.4.8.0.dylib] Error 1
make[1]: *** [modules/imgcodecs/CMakeFiles/opencv_imgcodecs.dir/all] Error 2
make: *** [all] Error 2
```

I get the above error when trying to install `opencv` on M1 iMac.

**Comment by cary-ilm** [comment]
This sounds similar to #1538, possibly discrepencies in how different compilers handle symbol export directives. Can you describe more about what compiler version you're using?

**Comment by cary-ilm** [comment]
Oh, no, I see you're building OpenEXR 3.2 against Imath 2.5, which should not be entirely impossible but may well cause problems. Can you describe more about exactly how you're building opencv?

**Comment by kafka-tamura** [comment]
I was able to resolve this. I realised that some Imath 2.5 needed to be upgraded. The data for my M1 Mac was imported from 2013 MacBook pro, so many of the libraries were outdated. I  updated the libraries 1 by 1 and was eventually able to install this. Don't remember the exact sequence of events I followed.
