### ISSUE TITLE
MacPorts deprecation needs to be removed

### ISSUE THREAD

**Issue by JGoldstone** [AcademySoftwareFoundation/openexr#1606]
In the Install section of the OpenEXR docs, we show how one would install via Homebrew, which is fine, but then we say "We do not recommend installation via Macports [sic] because the distribution is out of date". It's true that MacPorts is behind, at 3.1.11, whereas Homebrew is current with 3.2.1; but the MacPorts comment was inserted because they were incredibly out of date (as in didn't have an OpenEXR 3.x port for years). They deserve better.

Interestingly, I am pretty sure we *meant* to make a comparable comment re: MacPorts on the Imath install page, but someone typo'd, and it says "On macOS, we do not recommend installation via HomeBrew [sic] because the distribution is outdated". Homebrew is actually fully caught up at Imath 3.1.9...and so is MacPorts.

How would people feel about my preparing a PR that put MacPorts on an equal footing with Homebrew as far as macOS package manager installation goes?

I can nudge the maintainers to get MacPorts' Portfile for OpenEXR back to currency/parity.

Meanwhile I need to break it to Larry over on OpenImageIO that he can probably stop mentioning `fink` in his installation instructions.

**Comment by meshula** [comment]
A PR sounds to be in order. I don't think we need to caution about either homebrew or macports at the moment as there are folks such as yourself actively moving things along. Also, Happy New Year!

**Comment by cary-ilm** [comment]
Updated: #1611
