### ISSUE TITLE
Imath - Remove Enumerated Class and replace with Enum Class

### ISSUE THREAD

**Issue by 404Vector** [AcademySoftwareFoundation/openexr#1609]
https://github.com/AcademySoftwareFoundation/openexr/blob/86d0fb09859951d1e51a889e4ff2b7b3baecf021/src/wrappers/python/Imath.py#L68C1-L68C1

In older versions of Python, enum classes did not exist, and developers had to create them themselves if necessary.

However, the enum class was added starting with Python 3.4 version.

Therefore, using a self-defined class instead of using Python's default class causes confusion to developers.

Additionally, the enum class already supports the functions directly implemented in Enumerated and its child classes (LineOrder, Compression, etc.).
  - __repr__, __cmp__, __eq__, names, etc.

Therefore, unless you absolutely need to support very old versions (python2 and python3 below 3.4), I think it is a good idea to replace it.

**Comment by cary-ilm** [comment]
Our intention is to completely replace that `Imath.py` with a proper import of the bindings from the Imath project. The current contents are a remnant of a much earlier implementation that needs a serious update.

**Comment by 404Vector** [comment]
https://github.com/AcademySoftwareFoundation/openexr/pull/1756
