### ISSUE TITLE
Delete empty classic board

### ISSUE THREAD

**Issue by Vertexwahn** [AcademySoftwareFoundation/openexr#1614]
When visiting the openexr GitHub page you the Projects (1):

![image](https://github.com/AcademySoftwareFoundation/openexr/assets/3775001/d03d3f2f-e686-4748-8d7c-90fc03734145)

This board is empty - and useless:
https://github.com/AcademySoftwareFoundation/openexr/projects/1

Delete it!

**Comment by cary-ilm** [comment]
done.
