### ISSUE TITLE
CompressionAttribute::readValueFrom() should use isValidCompression()?

### ISSUE THREAD

**Issue by palemieux** [AcademySoftwareFoundation/openexr#1641]
Couldn't `isValidCompression()` be used here to avoid code duplication and make it easier to add/modify/remote compression schemes?

https://github.com/AcademySoftwareFoundation/openexr/blob/6905396791cd858715fb695fab253deff797f119/src/lib/OpenEXR/ImfCompressionAttribute.cpp#L57

**Comment by peterhillman** [comment]
#1616 will do this when it lands

**Comment by cary-ilm** [comment]
#1616 has landed
