### ISSUE TITLE
About 3.2.126 release

### ISSUE THREAD

**Issue by chenrui333** [AcademySoftwareFoundation/openexr#1665]
👋 not quite sure if 3.2.126 release intended, create this issue to double check on it. Thanks!

<img width="515" alt="image" src="https://github.com/AcademySoftwareFoundation/openexr/assets/1580956/0de0b068-fa26-44db-927c-1482b2c4fe6e">

relates to https://github.com/Homebrew/homebrew-core/pull/162905

**Comment by cary-ilm** [comment]
I maintain OpenEXR, and the 3.2.126 release was a mistake, the result of an automation script gone wrong. It's not a valid release anyone should use. 

OpenEXR 3.2.3 is the latest release, can you update to that? Apologies for the hassle that 126>3.

I deleted the release, although the tag still exists. I'd prefer to delete the tag entirely to reduce confusion. Will that cause a problem for you?

**Comment by chenrui333** [comment]
nope, I'd actually prefer deleting that tag so it wont cause issue on homebrew end :) Thanks!

**Comment by chenrui333** [comment]
@cary-ilm let me know when you have done it, so I can close this PR, https://github.com/Homebrew/homebrew-core/pull/165595. 🙏

**Comment by cary-ilm** [comment]
I've deleted the v3.2.126 tag.

For the record, the tag was 6905396791cd858715fb695fab253deff797f119

**Comment by chenrui333** [comment]
Thanks @cary-ilm!

**Comment by chenrui333** [comment]
@cary-ilm looks like the tag comes back again

![image](https://github.com/AcademySoftwareFoundation/openexr/assets/1580956/259cf19b-c062-4af8-a237-540167bf1279)

**Comment by cary-ilm** [comment]
Sorry, a push from clone that had the tag. I've removed it again.
