### ISSUE TITLE
tarball at https://github.com/AcademySoftwareFoundation/openexr/releases/download/v3.2.4/openexr-v3.2.4.tar.gz extracts incorrectly

### ISSUE THREAD

**Issue by rubyFeedback** [AcademySoftwareFoundation/openexr#1700]
Hey folks there,

When you extract:

https://github.com/AcademySoftwareFoundation/openexr/releases/download/v3.2.4/openexr-v3.2.4.tar.gz

I would expect the following directory to be created, in the current working directory:

openexr-v3.2.4/

Instead, it dumps **all** contents into the current working directory. This is wrong and unexpected. Hopefully
in the next release it would extract to openexr-v3.2.4/ or openexr-3.2.4/ (in general the only correct way
is to extract to exactly the same name as the tarball; quite many github based projects do this incorrectly).

**Comment by cary-ilm** [comment]
Apologies, that was an oversight, missing a `--prefix` for the `git archive`.

Do you have an recommendation for naming? The tag begins with `v` (e.g. `v3.2.4`), but GitHub's "Source Code" download link omits the `v` (e.g. `openexr-3.2.4.tar.gz` extracts to `openexr-3.2.4/...`).  Is it preferable to match that, or be distinct from it? Either way, I'll make sure the directory matches the tarball name.

**Comment by aclark4life** [comment]
You can probably drop the `v` in the tarball as it's typically only used to designate the number as version number when such designation is needed e.g. `git tag v1.2.3`. or `https://mirrors.edge.kernel.org/pub/linux/kernel/v6.x/`. When paired with the name of the software, it's less common to see the `v`. E.g.

<img width="684" alt="Screenshot 2024-03-27 at 8 23 48 PM" src="https://github.com/AcademySoftwareFoundation/openexr/assets/72164/fb1ab4da-99f6-4852-a690-aeb041e2c71f">

<img width="593" alt="Screenshot 2024-03-27 at 8 29 35 PM" src="https://github.com/AcademySoftwareFoundation/openexr/assets/72164/f85592d6-1b5b-44b3-959c-486ceb280d59">

Unrelated, but also interesting to note that v1.2.3 is **not** a [semantic version number](https://semver.org/#is-v123-a-semantic-version).

**Comment by cary-ilm** [comment]
Should be fixed in the next release.
