### ISSUE TITLE
Python crashes when trying to write an output file

### ISSUE THREAD

**Issue by hroskes** [AcademySoftwareFoundation/openexr#1711]
I'm running the example code from the README:
```
import OpenEXR, Imath

width = 10
height = 10
size = width * height

h = OpenEXR.Header(width,height)
h['channels'] = {'R' : Imath.Channel(Imath.PixelType.FLOAT),
                 'G' : Imath.Channel(Imath.PixelType.FLOAT),
                 'B' : Imath.Channel(Imath.PixelType.FLOAT),
                 'A' : Imath.Channel(Imath.PixelType.FLOAT)} 
o = OpenEXR.OutputFile("hello.exr", h)
r = array('f', [n for n in range(size*0,size*1)]).tobytes()
g = array('f', [n for n in range(size*1,size*2)]).tobytes()
b = array('f', [n for n in range(size*2,size*3)]).tobytes()
a = array('f', [n for n in range(size*3,size*4)]).tobytes()
channels = {'R' : r, 'G' : g, 'B' : b, 'A' : a}
o.writePixels(channels)
o.close()
```

When I get to the `OpenEXR.OutputFile`, I get a "Python has stopped working" dialog box, or a Jupyter dialog box "The kernel has stopped unexpectedly."

I'm running on 64-bit Miniconda on Windows 11, in a clean environment where I just installed python and jupyter, then pip installed OpenEXR.  I tried Python 3.12, then made a new environment with Python 3.7 (since that's the oldest version supported by the pyproject.toml).  I also tried in conda environments on a different computer running Windows Server 2016.  None of this works.

There's also a conda OpenEXR on conda-forge.  I tried with and without that; I'm not sure what it is, but installing it is not sufficient to `import OpenEXR` without also pip installing OpenEXR.

Please let me know if there's any more info, or tests I can run, that would be useful in debugging.

**Comment by cary-ilm** [comment]
Oops, sorry about that, that example code is wrong. I'll submit a fix momentarily, but the proper line should read  `Imath.Channel(Imath.PixelType(Imath.PixelType.FLOAT) )`. And it's also missing a `from array import array`.

**Comment by hroskes** [comment]
Thank you!  That works for me.

I made a PR (#1714) and am trying to figure out who from my institution I should reach out to about the CLA.  I'm hoping to get back to you about that later today.
