### ISSUE TITLE
Uninitialized sliceOptimizationData::type

### ISSUE THREAD

**Issue by matt77hias** [AcademySoftwareFoundation/openexr#1741]
The below code in [ImfScanLineInputFile.cpp](https://github.com/AcademySoftwareFoundation/openexr/blob/main/src/lib/OpenEXR/ImfScanLineInputFile.cpp#L1553):

```c++
sliceOptimizationData dat;
dat.base      = j.slice ().base;
dat.fill      = fill;
dat.fillValue = j.slice ().fillValue;
dat.offset    = offset;
dat.xStride   = j.slice ().xStride;
dat.yStride   = j.slice ().yStride;
dat.xSampling = j.slice ().xSampling;
dat.ySampling = j.slice ().ySampling;
optData.push_back (dat);
```
does not assign [`sliceOptimizationData::type`](https://github.com/AcademySoftwareFoundation/openexr/blob/main/src/lib/OpenEXR/ImfScanLineInputFile.cpp#L163).

Shouldn't `data.type = fill ? j.slice ().type : i.channel ().type;` be added?

**Comment by peterhillman** [comment]
Good point! Actually `type` is never used, because optimization only works if all the channels in optData are HALF channels, so a better solution would be to remove `sliceOptimizationData::type` completely.
If you'd like to make that change and put in a PR, then go ahead!

**Comment by matt77hias** [comment]
Moved to https://github.com/AcademySoftwareFoundation/openexr/pull/1742.
