### ISSUE TITLE
Error installing OpenEXR with pip

### ISSUE THREAD

**Issue by aarondemolder** [AcademySoftwareFoundation/openexr#1855]
I was excited to see the new python bindings but I'm having some trouble on macos Sonoma 14.5.

I'm not sure if this is an issue on my end or if something needs adjusting.

Log from pip attached:

[cmd_2024-10-01_17.00.40_pip_errors.log](https://github.com/user-attachments/files/17211800/cmd_2024-10-01_17.00.40_pip_errors.log)

**Comment by cary-ilm** [comment]
That looks like a problem with the distribution. It's incorrectly looking for a test directory that is not included with the sdist. I'll investigate further. 

It's a workaround for now, but you might try cloning the repo and building from source.

**Comment by aarondemolder** [comment]
Thanks Cary! No rush on my side really, let me know if it's handy for me to test anything

**Comment by RafaelWO** [comment]
I have the same issue. As far as I know OpenEXR usually ships pre-built binaries to PyPI but for some reason [version 3.3.0 does not include files for Python 3.12](https://pypi.org/project/OpenEXR/3.3.0/#files). Could this be part of the issue?

P.S. Version [3.2.4](https://pypi.org/project/OpenEXR/3.2.4/#files) does include builds for 3.12 though.

**Comment by RafaelWO** [comment]
I noticed that the [GH workflow for building Python wheels does not include Python 3.12](https://github.com/AcademySoftwareFoundation/openexr/blob/8d52f35c1bca8f263673e279d33280fef4889f81/.github/workflows/python-wheels.yml#L67). Happy to create a PR if this should be added :slightly_smiling_face: 

P.S. The Python 3.13 release is also [around the corner](https://peps.python.org/pep-0719/#schedule) :snake:

**Comment by cary-ilm** [comment]
Hmm, I had removed python 3.12 at one point during development because the build failed, but trying it again now, it does seem to work. Please do submit a PR, thanks!

#1857 should fix the sdist/macOS 14.5 problem, we'll make a patch shortly.

**Comment by RafaelWO** [comment]
> Hmm, I had removed python 3.12 at one point during development because the build failed, but trying it again now, it does seem to work. Please do submit a PR, thanks!

I create a PR: #1861 :slightly_smiling_face:

**Comment by jonwolski** [comment]
> I'm not sure if this is an issue on my end or if something needs adjusting.

Not just you.

Here's a minimal test case to reproduce the issue:

```
docker run -it python:3.11-bookworm python -m pip install openexr==3.3.0
```

I've tried `openexr==3.2.3`, `…==3.2.4`, and `…==3.3.0` all to the same effect.

I've also tried python 3.10, and bullseye instead of bookworm.

**Comment by cary-ilm** [comment]
This should be fixed in v3.3.1, released just now. Give the wheel an hour or so to get built.

**Comment by jonwolski** [comment]
Thank you a 2^20, @cary-ilm ! I have confirmed v3.3.1 works for me.

![You're a super hero](https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExNDFuNHdlanVjanF1NHg3cnltMGU3MnBnN3J5aDJmODJ2NXQ1ZmV3NCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/5aFCOdDCef6j1u74Pl/giphy.gif)

**Comment by cary-ilm** [comment]
Glad to hear it, thanks!

**Comment by aarondemolder** [comment]
Also now works for me!
Seeing as there's new issues for taking a look at pip install without a binary, I think this can be closed.
Thanks for the quick fix!
