### ISSUE TITLE
worldToCamera / m44f is `None` via python bindings

### ISSUE THREAD

**Issue by flipphillips** [AcademySoftwareFoundation/openexr#1926]
## Description

Trying to extract `worldToCamera` from EXR via Python. Is empty / `None`.

## Replication

```python
...
    exr = OpenEXR.InputFile("Scene.ViewLayer.0001.exr")
    header = exr.header()
...
    print(header['worldToCamera'])
...
None
```

## Regression / testing

```sh
❯ exrinfo --verbose Scene.ViewLayer.0001.exr | grep worldToCamera
  worldToCamera: m44f [ [0.866906 0.160843 0.471808 0] [-0.498471 0.279727 0.820536 0] [3.66805e-08 0.946511 -0.322673 0] [-0.187342 -0.00632298 13.006 1] ]
❯ oiiotool --info -v Scene.ViewLayer.0001.exr | grep worldToCamera
    worldToCamera: 0.866906, 0.160843, 0.471808, 0, -0.498471, 0.279727, 0.820536, 0, 3.66805e-08, 0.946511, -0.322673, 0, -0.187342, -0.00632298, 13.006, 1

Seems all `m44f` elements are `None` from python.
```

**Comment by cary-ilm** [comment]
That's using the old, deprecated API object `InputFile`, which has limited feature support.  Try this, using `File` instead:

```
    exr = OpenEXR.File("Scene.ViewLayer.0001.exr")
    header = exr.header()
    print(header['worldToCamera'])
```

**Comment by flipphillips** [comment]
That's what I get for reusing few-years old code... old APIs.

**Comment by lgritz** [comment]
@flipphillips That old python binding is not just years old, it was not developed as part of the OpenEXR project at all! After years of being a thorn in our side -- barely or un-maintained, hopelessly lagging the C++ API's evolution, and not coming from this team but everybody assuming that it was -- it was finally gifted to us a year or two ago. But it needed a full rewrite, so now there's a new one.

**Comment by flipphillips** [comment]
@lgritz Got it - makes sense... I'd love to know where I even scooped it up from, the comments in my code are, sadly, lacking :) Probably from some 'internal' friends somewhere. 

In summary - it is pilot error and doing it 'the right way' works, of course. Sorry for the false alarm.

**Comment by lgritz** [comment]
Well, "pip install openexr" got you those bindings, but they didn't actually come from this project! So the misunderstanding was very natural, but it was tough to not directly be able to fix anything on our end. It's great that the code and the PyPI name eventually ended up in the hands of the main project. Moving forward, we will always have the Python and C++ library bindings in sync.
