### ISSUE TITLE
Question about string encoding

### ISSUE THREAD

**Issue by pborsutzki** [AcademySoftwareFoundation/openexr#1927]
Hi folks,

first of all, thanks for the great library!
I am currently working on internationalization of my project that integrates OpenEXR. I tried to find out from the documentation and the source what encoding OpenEXR accepts/returns for its stings but did not find anything definitive. The only references to string encoding I found were in the docs for [`StandardAttributes.rst`](https://openexr.com/en/latest/StandardAttributes.html) where some camera metadata attributes should be UTF-8 encoded. But I failed to find something more general.

So the question is: Is there a convention in the project that readers and writers of the file format are sticking to? Or is it just "unspecified", like ASCII works for sure, anything beyond is "up to the implementation"? I guess I can just put UTF-8 or ISO/IEC 8859-1 encoded strings into it without breaking anything while writing, but without a common standard I can't rely on viewers to interpret this correctly.

Can you give me any hints at best practices? I am especially interested into encoding of header names, header attributes (names, StringAttribute), channel names and slice names.

Many thanks!

**Comment by peterhillman** [comment]
I think the short answer is not to expect any tool to display strings correctly if they aren't simple ASCII characters: they aren't common so wouldn't have had much testing. 

There is standardized naming for channels (e.g. R/G/B must be used for red/green/blue and '.' is a layer separator). In theory that would allow UTF-8 encoded channel names, but some encodings wouldn't be compatible with that standard. I don't think there's anything else in the library that enforces any encoding. StringAttributes are just arbitrary arrays of bytes. However, code written in languages with more explicit string encoding may well break.

**Comment by pborsutzki** [comment]
That's exactly what I feared. But at least it is somewhat documented now in this repository. Nevertheless, thank you for the quick answer!
