### ISSUE TITLE
OpenEXR build issue when already installed

### ISSUE THREAD

**Issue by HughMacdonald** [AcademySoftwareFoundation/openexr#200]
Hi,

I have a machine with OpenEXR 1.X installed on it. I'm building OpenEXR 2.2 into a separate location.

At one point, it fails:

```
make[1]: Entering directory `/mount/users/hughmacdonald/development/builds/USD/dependencies/src/openexr/OpenEXR/IlmImfUtil'
/bin/bash ../libtool  --tag=CXX   --mode=link g++ -pipe -g -O2 -L/mount/users/hughmacdonald/development/builds/USD/dependencies/install/IlmBase/lib  -L/usr/local/lib -version-info 22:0:0 -no-undefined -release 2_2  -o libIlmImfUtil.la -rpath /mount/users/hughmacdonald/development/builds/USD/dependencies/install/OpenEXR/lib ImfImageChannel.lo ImfFlatImageChannel.lo ImfDeepImageChannel.lo ImfSampleCountChannel.lo ImfImageLevel.lo ImfFlatImageLevel.lo ImfDeepImageLevel.lo ImfImage.lo ImfFlatImage.lo ImfDeepImage.lo ImfImageIO.lo ImfFlatImageIO.lo ImfDeepImageIO.lo ImfImageDataWindow.lo -L../IlmImf -lImath -lHalf -lIex -lIlmThread -lpthread -lIlmImf 
libtool: link: `/usr/local/lib/libIlmImf.la' is not a valid libtool archive
make[1]: *** [libIlmImfUtil.la] Error 1
```

this is because `-L/usr/local/lib` is on the command-line before `-L../IlmImf`,so it's finding the central install of libIlmImf.la from 1.X.

Moving `-L../IlmImf` to just before `-L/usr/local/lib` fixes the issue, and the rest of the build goes through fine.

Thanks

**Comment by cary-ilm** [comment]
Looking into the backlog of open OpenEXR issues.  This seems to have been resolved with the improvements to cmake.  Closing the issue for now, feel free to re-open or file a new issue if you need further help.
