### ISSUE TITLE
Documentation files disapeared!

### ISSUE THREAD

**Issue by weblucas** [AcademySoftwareFoundation/openexr#335]
All link to pdf are not available anymore

http://www.openexr.com/ReadingAndWritingImageFiles.pdf

**Comment by a-e-k** [comment]
Seems like the link is broken.  On a guess I tried http://www.openexr.com/documentation/ReadingAndWritingImageFiles.pdf instead and was able to reach it.

**Comment by cary-ilm** [comment]
Sorry, this should be fixed now. We swapped how the site was hosted, and I accidentally broke the links.
