### ISSUE TITLE
Missing lib dir for ilmbase on Windows

### ISSUE THREAD

**Issue by npavlovikj** [AcademySoftwareFoundation/openexr#347]
Hi,

I am trying to install "ilmbase-2.3.0.tar.gz" on Windows using "cmake" and "ninja". Although the build finishes ok and the "include" directory is created, there is no "lib" directory. Can you please tell me how I can include this directory in the build?
The command I am using is "_cmake -G "Ninja" -DCMAKE_PREFIX_PATH=%PREFIX% -DCMAKE_INSTALL_PREFIX=%PREFIX%_".

Thank you,
Natasha

**Comment by yellowtailfan** [comment]
This Windows build recipe might help:
https://stackoverflow.com/a/41418231

**Comment by ghost** [comment]
you could install the nugets: "nuget install openexr-msvc-x64" or "nuget install openexr-msvc-x86"
https://www.nuget.org/packages/openexr-msvc-x64/
https://www.nuget.org/packages/openexr-msvc-x86/

**Comment by RotemShi** [comment]
> This Windows build recipe might help:
> https://stackoverflow.com/a/41418231

Having the same issue. Running this recipe does not help.

**Comment by yellowtailfan** [comment]
Here's a simpler recipe:
* Build zlib from source, creating a 2 folders inside the inside the top-level zlib source folder:
  * a bin folder containing the zlib DLL and 
  * a lib folder containing *.lib libraries
* Download OpenEXR using the Github source code link on the [releases page](https://github.com/openexr/openexr/releases):
  * E.g. https://github.com/openexr/openexr/archive/v2.3.0.zip
  * Don't use the *.tar.gz files
* Unzip to openexr-win/openexr-2.3.0
```
> cd openexr-2.3.0
> cmake -DCMAKE_INSTALL_PREFIX=..\deploy . -G "Visual Studio 14 Win64" -DCMAKE_PREFIX_PATH=..\zlib-1.2.11 -DOPENEXR_BUILD_PYTHON_LIBS=0
> cmake --build . --config Release --target INSTALL
```
  * In the first cmake line above,  `..\zlib-1.2.11` is the path to the zlib source folder containing the bin and lib folders mentioned above

**Comment by RotemShi** [comment]
@yellowtailfan Thank you, that's what I ended up doing and it worked.

**Comment by meshula** [comment]
@yellowtailfan's solution is correct. In a future release, the tar.gz files will also work, but that's not the case yet.
