### ISSUE TITLE
PyIlmbase 2.3 usage

### ISSUE THREAD

**Issue by npavlovikj** [AcademySoftwareFoundation/openexr#349]
Hi,

I built "pyilmbase" 2.3.0 with "boost" 1.68.0, "ilmbase" 2.3.0, "python" 3.6.6 and "gcc" 7.3.0.
I used the following command:
**./configure --enable-cxxstd=11 --with-boost-include-dir="${PREFIX}/include" --with-boost-lib-dir="${PREFIX}/lib" --with-ilmbase-prefix="${PREFIX}"**
and everything built successfully.
In my "_/lib/python*/site-packages/_" directory I can see "_iexmodule.so_", "_imathmodule.so_" and "_imathnumpymodule.so_", and in "_lib_" I have "_libPyIex.so_" and "_libPyImath.so_".
I set the _LD_LIBRARY_PATH_ and _LDFLAGS_ accordingly; however, when I try to import any module I get errors, e.g.:
**>>> import iex**
_Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'iex'_
**>>> import iexmodule**
_Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /envs/lib/python3.6/site-packages/iexmodule.so: undefined symbol: _ZN7Iex_2_37BaseExcC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE_

I read that the latter error occurs when "boost" is not properly linked.
However, the "boost" libraries were properly set and used during the installation.

Can you please tell me if this is the proper way of using "_pyilmbase_", and if so, how can I fix the issue I am getting?

Thank you,
Natasha

**Comment by sopvop** [comment]
You probably compiled boost with `-D_GLIBCXX_USE_CXX11_ABI=0`.
You should either compile boost without it,or openexr with it.

**Comment by cary-ilm** [comment]
Looking into the OpenEXR backlog, is this still an issue?

**Comment by cary-ilm** [comment]
Closing the issue for now, feel free to re-open or file a new issue if you need further help.
