### ISSUE TITLE
IlmImf DLL installed in the wrong folder

### ISSUE THREAD

**Issue by yellowtailfan** [AcademySoftwareFoundation/openexr#355]
The IlmImf DLL install path seems to be missing the user-supplied prefix (CMAKE_INSTALL_PREFIX).

I downloaded https://github.com/openexr/openexr/archive/v2.3.0.zip and built it using:

```
cd openexr-2.3.0
cmake -DCMAKE_INSTALL_PREFIX=..\deploy . -G "Visual Studio 14 Win64" -DCMAKE_PREFIX_PATH=..\zlib-1.2.11 -DOPENEXR_BUILD_PYTHON_LIBS=0
cmake --build . --config Release --target INSTALL
```

This was using a previous static build of zlib, built  using this recipe: 

https://stackoverflow.com/a/41418231

All of the DLLs were built and installed successfully into ..\deploy\bin, except IlmImf_2-3.dll, which was incorrectly installed into c:\bin. 

I was getting an import failure with the OpenEXR Python wrapper from excamera due to a missing DLL, and I only figured it out because by doing a global file system search which found IlmImf_2-3.dll in c:\bin. I moved it into ..\deploy\bin and the import now works successfully.

**Comment by crud89** [comment]
I can confirm and reproduce this issue. I've also found a workaround and created the pull request https://github.com/openexr/openexr/pull/366 regarding it.

As a workaround, replace the occurencies of `${OPENEXR_PACKAGE_PREFIX}` in the `./OpenEXR/IlmImf/CMakeLists.txt` file with `${CMAKE_INSTALL_PREFIX}` and reconfigure your project. You can also use [this fork](https://github.com/Aschratt/openexr) directly.

Here are the affected lines:

    IF (WIN32)
      #SET(RUNTIME_DIR ${OPENEXR_PACKAGE_PREFIX}/bin)
      SET(RUNTIME_DIR ${CMAKE_INSTALL_PREFIX}/bin)
      SET(WORKING_DIR ${RUNTIME_DIR})
    ELSE ()
      #SET(RUNTIME_DIR ${OPENEXR_PACKAGE_PREFIX}/lib)
      SET(RUNTIME_DIR ${CMAKE_INSTALL_PREFIX}/lib)
      SET(WORKING_DIR .)
    ENDIF ()

**Comment by meshula** [comment]
This should be good now, thanks for the report and suggested fix. Please reopen if it's still broken.
