### ISSUE TITLE
Move ILMBASE_HAVE_CONTROL_REGISTER_SUPPORT to a private header

### ISSUE THREAD

**Issue by malaterre** [AcademySoftwareFoundation/openexr#357]
Currently `ILMBASE_HAVE_CONTROL_REGISTER_SUPPORT` is being tested and then defined in a public header that will get installed:

```
config/IlmBaseConfig.h.in:#undef ILMBASE_HAVE_CONTROL_REGISTER_SUPPORT
```

This is an issue for us at least in the context of cross compiling since now the header on -say- armhf and amd64 will be different.

Would it be possible to move this define to some kind of private header which wont be installed as part of the standard installation. Another possibility is simply to pass this definition on the command line using -D. This way this is not explicitly visible in the header file.

**Comment by meshula** [comment]
This flag exists only for the implementation of 

```c
void setFpExceptionHandler (FpExceptionHandler handler);
```
I agree that this flag should be hidden within the implementation.

**Comment by kdt3rd** [comment]
This has been implemented, there are now two auto-generated headers, one for internal things, and one for the public namespace configuration, etc.
