### ISSUE TITLE
[VS2015] Compile error C2782: 'ssize_t' in PyImathFixedMatrix

### ISSUE THREAD

**Issue by JenusL** [AcademySoftwareFoundation/openexr#359]
I'm building OpenEXR with Python 3.6 bindings on Windows with Boost 1.66 and MSVC 14 (VS2015).
I got the following compile error:
`openexr\pyilmbase\pyimath\PyImathFixedMatrix.h(144): error C2872: 'ssize_t': ambiguous symbol`

As far as I can tell that is the only use of `ssize_t` in the whole project. I changed it to `Py_ssize_t` to get it to compile but I don't know if that is the proper solution.

**Comment by meshula** [comment]
Good catch. Not only should Py_ssize_t be used, but convert_index should be fixed to take and return a Py_ssize_t instead of an it.

**Comment by cary-ilm** [comment]
Fixed in #415
