### ISSUE TITLE
Specified Boost.Python not found on Boost versions < 1.67

### ISSUE THREAD

**Issue by JenusL** [AcademySoftwareFoundation/openexr#360]
Boost changed how the python files was named in Boost 1.67. This affects how we search for the Boost.Python component with find_package in CMake.

**Boost < 1.67**
Python 2.7 name: `python`
Python 3.6 name: `python3`

**Boost >= 1.67**
Python 2.7 name: `python27`
Python 3.6 name: `python36`

Current CMakeList is looking for python like this:
`find_package(Boost COMPONENTS python${OPENEXR_PYTHON_MAJOR}${OPENEXR_PYTHON_MINOR})`
This only works on Boost >= 1.67 and will always fall back to default with earlier boost versions.

I already have a fix for this in my branch and will create a PR.

**Comment by cary-ilm** [comment]
PR is merged, so closing, thanks.
