### ISSUE TITLE
`OpenEXRSettings.cmake` is missing from the release tarball

### ISSUE THREAD

**Issue by SylvainCorlay** [AcademySoftwareFoundation/openexr#363]
This prevents from building openexr in a standalone fashion on windows with the release tarball.

**Comment by kdt3rd** [comment]
A complete refactor of the cmake has taken place, modernizing cmake to match the "Modern CMake" guidelines and practices, and deployment scripts updated, so this should be fixed in the next release we make. Thanks for the report!
