### ISSUE TITLE
undefined symbol: _ZTIN7Iex_2_27BaseExcE

### ISSUE THREAD

**Issue by zkailinzhang** [AcademySoftwareFoundation/openexr#380]
`pip3 install openexr`
  Using cached https://files.pythonhosted.org/packages/7c/c4/76bf884f59d3137847edf8b93aaf40f6257d8315d0064e8b1a606ad80b1b/OpenEXR-1.3.2.tar.gz
Building wheels for collected packages: openexr
  Building wheel for openexr (setup.py) ... done
  Stored in directory: /home/zn/.cache/pip/wheels/41/06/9f/c7dc838815b0e7dfc7d7dc19cc3d677edb47594d8489adc62a
Successfully built openexr
Installing collected packages: openexr
Successfully installed openexr-1.3.2

`python`
Python 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
`>>> import openexr`
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'openexr'
`>>> import OpenEXR`
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /home/zn/anaconda3/envs/pvnet/lib/python3.6/site-packages/OpenEXR.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZTIN7Iex_2_27BaseExcE

my pc is ubuntu 16 64bit, python3.6

**Comment by meshula** [comment]
The repo for pyopenexr is over here: https://github.com/jamesbowman/openexrpython
It would be a good idea to post there so the authors of the python openexr module can see it.

**Comment by cary-ilm** [comment]
Following up on this, this doesn't seem to be an issue with OpenEXR, but rather with openexrpython, not supported by the OpenEXR project.
