### ISSUE TITLE
constexpr all the things, and noexcept

### ISSUE THREAD

**Issue by lgritz** [AcademySoftwareFoundation/openexr#385]
We're in a C++11 world (and indeed C++14 if you take VFX Platform literally). A huge amount of Imath should be marked constexpr, and for that matter there should be noexcept littered all over the place.

What I did in OIIO is directly 'constexpr' the things that could be so in C++11, and define a macro (we could call it ILMBASE_CONSTEXPR14, say) that would `#define` to constexpr if it detects C++ >= 14 but define to nothing for C++11. Maybe similar for 17 and 20. Then in the future as we raise the C++ floor, we can eventually make them unconditional constexpr.

It would also be helpful to `noexcept` all the things that aren't designed to throw exceptions.

Both of these are utterly trivial to do for any individual function, the pain is merely that there are dozens of headers to overhaul.

It shouldn't affect "source compatibility" -- in the sense that adorning Imath with constexpr and noexcept will not cause anybody to need to edit client software that uses libIlmbase, only to recompile to get the goodness.

**Comment by RajatYolo** [comment]
Hi,
I would like to work on this, can you share the mailing list so that I can updates time to time.
Thanks.

**Comment by patlefort** [comment]
While we're at it, [[nodiscard]] (c++17 attribute) all the things too, the vast majority of functions with return values shouldn't be discarded.

**Comment by meshula** [comment]
see also https://github.com/AcademySoftwareFoundation/Imath/pull/95

**Comment by lgritz** [comment]
I believe that Imath 3.0 has done as much noexcept and constexpr as possible. Closing.
