### ISSUE TITLE
Make Imath headers Cuda-safe

### ISSUE THREAD

**Issue by lgritz** [AcademySoftwareFoundation/openexr#386]
You can make a macro like this:

```
// IMATH_HOSTDEVICE is used before a function declaration to supply the
// function decorators needed when compiling for CUDA devices.
#ifdef __CUDACC__
#    define IMATH_HOSTDEVICE __host__ __device__
#else
#    define IMATH_HOSTDEVICE
#endif
```

and then decorate lots of Imath functions with this.

That makes the headers safe to include when compiling code for Cuda.

You can see an example of this from the very unfortunate case of how we had to replicate (ugh) several Imath headers in OSL for the ongoing work to make an OptiX/Cuda back end for OSL shaders, e.g., take a look here: https://github.com/imageworks/OpenShadingLanguage/blob/master/src/include/OSL/ImathVec_cuda.h#L211

And you can see that we had to do this for several files:
https://github.com/imageworks/OpenShadingLanguage/tree/master/src/include/OSL

If Imath is so adorned, OSL can switch back to using Ilmbase as a pure dependency rather than have altered copies embedded in it. And surely this is not the only software that has exactly this problem.

The macros are harmless when not compiling for Cuda.

**Comment by lgritz** [comment]
I should clarify my imprecise language: It's not that the Imath headers are not *safe* to compile in Cuda. It's just that you can't *call* any of these handy functions or methods from other `__DEVICE__` (Cuda-side) functions or from Cuda kernels.

**Comment by kdt3rd** [comment]
A bit orthogonal to the rest of Imath, but there is the half type in cuda. It is trivial to fix IlmBase half.h to avoid re-defining half, however, have you studied if that is safe to drop in in place (I assume it auto-handles the ptx float <-> half conversions, so why would we re-create those), or if there are missing operators?

**Comment by meshula** [comment]
@lgritz This is done, isn't it, so we can close?

**Comment by lgritz** [comment]
Long since done!
