### ISSUE TITLE
Matrix22

### ISSUE THREAD

**Issue by lgritz** [AcademySoftwareFoundation/openexr#387]
Isn't it curious that Imath has always had Vec2, Vec3, Vec4, and Matrix33, Matrix44... hey, one of these things is not like the other.

OSL heavily uses Imath for its internal vector/matrix types, and I had a case of needing 2x2 matrices, so I did this years ago:
https://github.com/imageworks/OpenShadingLanguage/blob/master/src/include/OSL/matrix22.h

I never sent it back upstream to the OpenEXR project because at the time there appeared to be nobody interested in reviewing or merging PRs. But now there is! It is handy to have a 2x2 matrix type that is analogous to the 3x3 and 4x4. So here you go, I've already done most of the work. Not 100% of the work, though -- although it's been several years, I sort of recall that I may have taken a couple shortcuts by maybe not doing every last thing that I found in the 3x3 case. So maybe it's 90% of the way there and could probably use somebody who is a real stickler for Imath internals details to find anyplace I haven't done a full job with it (and it could also use some unit tests).

**Comment by meshula** [comment]
looks nice. I'd like to see this in the lib.

**Comment by mridullpandey** [comment]
hey @lgritz i want to work on this issue kindly let me know how to get started

**Comment by lgritz** [comment]
The OSL project has a matrix22.h file that is essentially a copy of material in OpenEXR's ImathMatrix.h (which has Matrix33 and Matrix44), but obviously altered to implement the 2x2 case. It seems natural to copy this material back to ImathMatrix.h, and then reconcile the various differences or anything relevant that was left out of the OSL version.

It's not exactly rocket science, but it probably does require understanding reasonably well the purpose and workings of what is already in ImathMatrix.h. If you know what the Matrix33 and Matrix44 classes are, what they are for, and how they work, then extending to the 2x2 case (with or without borrowing back from OSL's implementation) ought to be fairly straightforward. To do it well also would require adding analogous tests to whatever unit tests the 3x3 and 4x4 case have in the OpenEXR project. I didn't try to do that on the OSL side.

It's a "good first issue" in the sense of being quite independent of the rest of either the OpenEXR or OSL code bases, requires no understanding of the OpenEXR file format itself, can't really break anything else. But it's not a just-a-few-lines-of-code project. Definitely would be good to try if you feel up to it, it would be a lot bigger than the tiny qualifying test project that most students are shooting for. If you don't know what matrices are for, it's going to be difficult, I don't think we have time to teach you that. But if you come already knowing the math, see the 3x3 and 4x4 and think to yourself, "aha, I know what to do to extend this to 2x2", then it's probably just a couple days of work.

**Comment by owdt-magic** [comment]
I can take a crack at this, not sure about implementing tests though. Everything else seems straight forward.
