### ISSUE TITLE
fix -Wall compiler warnings

### ISSUE THREAD

**Issue by cary-ilm** [AcademySoftwareFoundation/openexr#389]
IlmBase and OpenEXR give many warning from -Wsign-compare -Wreorder, -Wswitch, -Wunused-but-set-variable, -Wmisleading-indentation, -Wunused-function, when compiled with C++14. These should be cleaned up.

**Comment by kdt3rd** [comment]
The code base now compiles cleanly on gcc 9 using "-Wall -Wsign-compare -Wreorder -Wswitch -Wunused-but-set-variable -Wmisleading-indentation -Wunused-function" and clang 8 with similar options.

This process even found an (unreported) copy/paste bug in pyilmbase with vector 4 - the 'w' component wasn't being copied on input.
