### ISSUE TITLE
Document the project policy on naming of .so's

### ISSUE THREAD

**Issue by cary-ilm** [AcademySoftwareFoundation/openexr#390]
The naming conventions for .so's, e.g. libImath-2_3.so.24.0.0 should be clearly laid out in the repo documentation, where the meaning of the numbers and the rationale for the naming is made easy to follow.

This is especially important since the project supports generating these by both CMake and autoconf.

**Comment by kdt3rd** [comment]
I have added a section to the INSTALL.md on my PR #490, please suggest comments / fixes there
