### ISSUE TITLE
Build for mac using cmake to Xcode fails to compile

### ISSUE THREAD

**Issue by kdt3rd** [AcademySoftwareFoundation/openexr#455]
Mac builds work fine if you run with makefiles or ninja generator, but if you generate for Xcode, the builds fail. However, it seems to be an issue with dependencies between the build stages generated by cmake (i.e. generating the headers, the libraries, etc.), and if you go through the dependency chain manually, each successive step can build. Based on the bug reports on cmake.org / kitware, it appears to be an issue with the object library mechanism, and some build-artifact thing that Xcode does. There does not seem to be anything code-wise to be done until cmake fixes the issue, however we should probably document this known failure case.

OpenSubdiv has explicitly warned against building using Xcode due to the same issues:
https://graphics.pixar.com/opensubdiv/docs/cmake_build.html

**Comment by meshula** [comment]
Could you link a report on the kitware site? The OpenSubdiv site mentions a problem, but not the particulars.

**Comment by kdt3rd** [comment]
There are a few, but these two are good representative issues:
https://gitlab.kitware.com/cmake/cmake/issues/17500
https://gitlab.kitware.com/cmake/cmake/issues/18088

If I remove the ability for both types of libraries at once using the object library mechanism, it seems to work ok, maybe I'll just do that when the xcode generator is running...

**Comment by kdt3rd** [comment]
Found the single sentence in the add_library docs in the official docs saying what I was doing isn't going to work for xcode for now, so just changed the mechanism, so if you are building both static and shared libraries under xcode, you'll have to incur a double compile for the time being

**Comment by meshula** [comment]
Thanks for the links; I understand the problem now. Trying to make it work would involve shenanigans to little gain, that's for sure.
