### ISSUE TITLE
Wrong LC_RPATH after make install (cmake setup on macos)

### ISSUE THREAD

**Issue by axxel** [AcademySoftwareFoundation/openexr#461]
Tools like `exrheader` compile and work just fine inside the build-tree (multiple `LC_RPATH` commands for the different libraries are set correctly). Then after `install` they are all replaced with one entry but that is wrong (`otool -l`):
``` 
path @rpath:/Users/Axel/contrib/openexr.root/lib (offset 12)
```
Result when executing the binary:
```
dyld: Library not loaded: @rpath/libIlmImf-2_3.24.dylib
  Referenced from: /Users/Axel/contrib/openexr.root/bin/./exrheader
  Reason: image not found
Trace/BPT trap: 5
```

**Comment by axxel** [comment]
"Needs Info" tag means "Issue is waiting for more information from the submitter." What information do you need from me?

**Comment by kdt3rd** [comment]
can you let me know the cmake config / gen line you used?

**Comment by kdt3rd** [comment]
And thanks for testing! :100:

**Comment by axxel** [comment]
I could not remember, since I simply pulled into an existing repo/build-dir. Hence, setup a fresh build dir:
```
cmake -DBUILD_TESTING=OFF -DPYILMBASE_ENABLE=OFF -DCMAKE_INSTALL_PREFIX=install ../openexr.git/
```
Same result. Note: I'm running an outdated macos (10.11.6). This fails with both the stock compiler as well as with a somewhat recent homebrew clang-6.

**Comment by kdt3rd** [comment]
after waiting for my mac to update, I am able to easily repro, will get it sorted today
