### ISSUE TITLE
Windows Environment Continuous Analysis build

### ISSUE THREAD

**Issue by ghost** [AcademySoftwareFoundation/openexr#504]
The appveyor system is available for windows continuous integration. It is possible to leverage appveyor and the MSBuild code analysis feature to continuously analyze the code for suggested quality improvements. 
Edit: the azure pipelines system is also available for windows continuous integration. Both options will be prepared for evaluation by the administrators.

**Comment by ghost** [comment]
@cary-ilm  should I rewrite for azure pipelines? that is not much effort on my end, but I need some direction here.  Who should get @ mention for code review?
https://github.com/openexr/openexr/pull/507

**Comment by meshula** [comment]
The ASWF (of which OpenEXR is a part), is using Azure, so that seems the best direction. https://lists.aswf.io/g/tac/topic/31715562?p=Created,,,20,2,0,0

**Comment by cary-ilm** [comment]
The Azure dashboard is here: https://dev.azure.com/openexr/OpenEXR

Closing the issue for now.
