### ISSUE TITLE
OpenEXR NuGet requires ZLib Nuget

### ISSUE THREAD

**Issue by ghost** [AcademySoftwareFoundation/openexr#506]
The installation of OpenEXR NuGet should automatically install the required ZLib Nuget.

**Comment by cary-ilm** [comment]
@coast77777777777, is this something you can look into resolving yourself?

**Comment by ghost** [comment]
Yea I will update the nuget to automatically install zlib.

**Comment by cary-ilm** [comment]
Closing the issue for now, feel free to re-open or file a new issue if you need further help.
