### ISSUE TITLE
A confused problem in the EXR to JPEG

### ISSUE THREAD

**Issue by hqqxyy** [AcademySoftwareFoundation/openexr#511]
Hi,

In the [document ](https://excamera.com/articles/26/doc/intro.html#openexr-to-jpg), the normalization seems not correct.

```
    extrema = [im.getextrema() for im in rgbf]
    darkest = min([lo for (lo,hi) in extrema])
    lighest = max([hi for (lo,hi) in extrema])
    scale = 255 / (lighest - darkest)
    def normalize_0_255(v):
        return (v * scale) + darkest
    rgb8 = [im.point(normalize_0_255).convert("L") for im in rgbf]
```

it might be
```
    extrema = [im.getextrema() for im in rgbf]
    darkest = min([lo for (lo,hi) in extrema])
    lighest = max([hi for (lo,hi) in extrema])
    scale = 255 / (lighest - darkest)
    def normalize_0_255(v):
        return (v - darkest) * scale
    rgb8 = [im.point(normalize_0_255).convert("L") for im in rgbf]
```

I am not sure whether it is a bug. If not, I feel sorry to bother you.

Best,

**Comment by peterhillman** [comment]
The python "OpenEXR" module, and its documentation, is not part of this OpenEXR project: it is an independent effort. You could follow up with the developers here: https://pypi.org/project/OpenEXR/
 
For what it's worth, I agree with you that your proposed normalization seems more correct (issue #421 also discusses normalization of OpenEXR images)
