### ISSUE TITLE
The OpenEXR_viewer can't be installed successfully due to the Cg support

### ISSUE THREAD

**Issue by minygd** [AcademySoftwareFoundation/openexr#529]
Hello, sorry to bother you. But I have tried days to apply the OpenEXR on my system, namely Linux Mint Tina(Maybe treat it as Ubuntu 18.04).
After dealing with the error reported in the community, I was suck by the difficulty set by the OpenEXR_Viewers. 
I have already download Nvidia-Cg-Toolkit from the https://developer.nvidia.com/cg-toolkit.
The supported file is:Cg-3.1_April2012_x86_64.deb
I make everything install in the /usr/local.
Things seem go good, but when I use the commend:

>  sudo ./configure

The system report:
`
checking for Cg... no

*** **The Cg test program could not be compiled.**
*** Possible reasons:
***     - The Cg libraries and includes are not installed.
***     - configure cannot find Cg (use the
***       --with-cg-prefix option to tell configure where
***       to find it).
***     - Your version of Cg is out of date.  Please update it
***       to the latest version.
***
*** The exrdisplay program will not be built with fragment shader
*** support because the fragment shader support depends on Cg.
checking for ANSI C header files... (cached) yes
checking limits.h usability... yes
checking limits.h presence... yes
checking for limits.h... yes
checking for unistd.h... (cached) yes
checking for an ANSI C-conforming const... yes
checking for inline... inline
checking for size_t... yes
checking for gcc optimization flags... -pipe
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating config/Makefile
config.status: creating exrdisplay/Makefile
config.status: creating playexr/Makefile
config.status: creating doc/Makefile
config.status: creating config/OpenEXR_ViewersConfig.h
config.status: config/OpenEXR_ViewersConfig.h is unchanged
config.status: executing depfiles commands
config.status: executing libtool commands

---------------------------------------------
Summary for OpenEXR features:

build exrdisplay FLTK application		yes
    with fragment shader support		no
ctl support                                     no

---------------------------------------------
`

It confused me so much during the day, can you give me some suggestions?

By the way, the CTL is miss in the SourceForge, anyway.

**Comment by kdt3rd** [comment]
The OpenEXR viewers are consider optional. Given that many tools just read them and display them better, our viewers have become outdated. So they are still there, but treated as an "add-on", so if you are using the configure scripts, which you seem to be (vs. cmake), this should be the third portion of the repository to compile, which you can just skip - you should already have the main part and tools of the exr library (i.e. exrheader, exrmaketiled, etc.) and the libraries themselves which you can use. However, if you would like to get them compiled, I believe I had to manually specify the Cg include folders and link arguments using CXXFLAGS and LDFLAGS the last time I used the configure scripts, as nvidia had changed the folders from what is expected.

Out of curiousity, which release are you trying to compile? An actual release or the master branch?

**Comment by minygd** [comment]
I use an actual release downloaded from https://www.openexr.com/downloads.html

So do I use './configure --with-cg-prefix=xxx'  make sense?

Thank you for your reply!
