### ISSUE TITLE
cmake errors when used as sub-project via add_subdirectory()

### ISSUE THREAD

**Issue by mmp** [AcademySoftwareFoundation/openexr#555]
If I try using the beta as a sub-project in a bigger system, via ADD_SUBDIRECTORY(src/ext/openexr) in my top-level CMakeLists.txt file, I get the errors below. (I don't see these if I just build OpenEXR as is.)

```
- Configure ILMBASE Version: 2.4.0 Lib API: 24.0.0
CMake Error at src/ext/openexr/IlmBase/config/CMakeLists.txt:28 (set_target_properties):
  Attempt to promote imported target "Threads::Threads" to global scope (by
  setting IMPORTED_GLOBAL) which is not built in this directory.


-- Configure OpenEXR Version: 2.4.0 Lib API: 24.0.0
CMake Error at src/ext/openexr/OpenEXR/config/CMakeLists.txt:53 (set_target_properties):
  Attempt to promote imported target "ZLIB::ZLIB" to global scope (by setting
  IMPORTED_GLOBAL) which is not built in this directory.
```

**Comment by mmp** [comment]
...and while removing those lines fixes use as a subproject, it leads to a bunch of warnings like this if I try to build openexr standalone...

```
CMake Error at OpenEXR/exrenvmap/CMakeLists.txt:4 (add_executable):
  Target "exrenvmap" links to target "ZLIB::ZLIB" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
```

**Comment by kdt3rd** [comment]
Matt - I've put in a PR that fixes this for me. I created a dummy a.out project and was able to use add_subdirectory to cleanly pull in OpenEXR. Not sure what O.S. / version you are running under, but I've minimally tested under ubuntu 18.04, CentOS 7.6 (with epel to pull in cmake3), Arch Linux.

Don't forget, you may want to disable PyIlmBase and the OpenEXR_Viewers if you aren't using them to save build time (although they should just warn and not error if you don't have all the prereqs).

**Comment by kdt3rd** [comment]
Merged, confirmed as fixed
