### ISSUE TITLE
throwErrno symbols missing when Iex is linked before other libraries statically

### ISSUE THREAD

**Issue by skurmedel** [AcademySoftwareFoundation/openexr#566]
I'm not sure anything can be done about this, but in case someone else has this problem, I'll file it. I won't be offended if its closed :)

We got symbol errors when OpenEXR tried to throw an exception based on an errno. We linked OpenEXR statically and the link order was "Half Iex ...[rest]". This caused a symbol error when it tried to call throwErrno. By moving Iex to the end of the link order, we fixed this issue.

**Comment by cary-ilm** [comment]
Yeah, I'm pretty sure this is standard linker behavior, symbols are searched for left to right. But to be clear - this link order is in your application Makefile, not from OpenEXR's build files, right?

**Comment by skurmedel** [comment]
Yeah, it was the order in our CMake scripts. Probably nothing OpenEXR can do about it.

**Comment by cary-ilm** [comment]
Closing the issue for now, feel free to re-open or file a new issue if you need further help.
