### ISSUE TITLE
Test failure on ARMv7

### ISSUE THREAD

**Issue by mbakke** [AcademySoftwareFoundation/openexr#571]
Hello,

I'm getting a "bus error" from `testLargeDataWindowOffsets` when running the OpenEXR 2.4.0 test suite on ARMv7 GNU/Linux.

Full log available here:
https://ci.guix.gnu.org/log/2znpz2fzjp84kaxzkjv98clpn9pnpb62-openexr-2.4.0

**Comment by peterhillman** [comment]
I've reproduced this now. It is a similar problem to issue #452, with non-aligned floats being accessed. It's in the test itself, not in the core library. I will address this by making the test use four bytes of space for every sample value.

**Comment by peterhillman** [comment]
Pull Request #598 fixes this and has now been merged
