### ISSUE TITLE
ImfFrameBuffer.h not compatible with C++98 code

### ISSUE THREAD

**Issue by clopez** [AcademySoftwareFoundation/openexr#579]
Since commit 119eb2d4672e5c77a79929758f7e4c566f47c794  ImfFrameBuffer.h includes `cstdint`

And `cstdint` is a C++11 header, so now including `ImfFrameBuffer.h` on any C++98 code will fail to build.

A possible fix is including `stdint.h` instead of   `cstdint` on `ImfFrameBuffer.h`

See for example https://gitlab.freedesktop.org/gstreamer/gst-plugins-bad/issues/1089 for a build failure this has caused

**Comment by cary-ilm** [comment]
The Technical Steering Committee has made the decision to adopt C++11 going forward and drop support for C++98 in the interest of clarity in the code and ease of maintenance. This means that 2.4.0+ releases won't compile on older systems, at least not without local changes.
