### ISSUE TITLE
Python modules are not linked to Boost::python

### ISSUE THREAD

**Issue by antonio-rojas** [AcademySoftwareFoundation/openexr#594]
When building pyilmbase with cmake, python modules don't link to Boost::python. This gives undefined symbol errors when trying to import them

**Comment by JenusL** [comment]
I tried to build OpenEXR 2.4 on Windows for the first time yesterday and I can confirm this.
```
LINK : fatal error LNK1104: cannot open file 'boost_python37-vc140-mt-x64-1_70.lib' [C:\Users\lindg\GitHub\vfxplatform_build\build\openexr\PyIlmBase\PyIex\iex_python3.vcxproj]
LINK : fatal error LNK1104: cannot open file 'boost_python37-vc140-mt-x64-1_70.lib' [C:\Users\lindg\GitHub\vfxplatform_build\build\openexr\PyIlmBase\PyImath\imath_python3.vcxproj]
```
So it affects only PyIex and PyImath. PyImathNumpy builds successfully.
Looking at the CMakeLists.txt for the three modules, I notice that they are fundamentally different and only in PyImathNumpy CMakeLists.txt there's code for linking to Boost::Python.
