### ISSUE TITLE
Broken pkgconfig files when building with cmake

### ISSUE THREAD

**Issue by antonio-rojas** [AcademySoftwareFoundation/openexr#595]
When building with cmake, the produced pkgconfig files are broken: libdir and includedir are missing ${prefix}

**Comment by cary-ilm** [comment]
Related to #592, @kdt3rd will investigate.

**Comment by StefanBruens** [comment]
This is still incorrect:

CMAKE_INSTALL_LIBDIR may be either an absolute or relative path, so always prefixing it is wrong.

There are two possible solutions:
- calculate the path relative to CMAKE_INSTALL_PREFIX
- just use CMAKE_INSTALL_FULL_LIBDIR

https://cmake.org/cmake/help/v3.16/module/GNUInstallDirs.html

Dito for INCLUDEDIR

exec_prefix should be dropped completely - it is an unused variable. Variables are local only.
