### ISSUE TITLE
PyIlmBaseConfig not in export set?

### ISSUE THREAD

**Issue by cbdwtv** [AcademySoftwareFoundation/openexr#604]
Hello,

I am attempting to build the latest commit, (mainly because it had the boost module link fixes), and came across this error in my cmake run:

```
-- Configuring done
CMake Error: install(EXPORT "PyIlmBase" ...) includes target "PyImath_Python2_7" which requires target "PyIlmBaseConfig" that is not in the export set.
```

I was wondering what I might be missing to be able to force that to correct itself. I set DPYILMBASE_BUILD_SUPPORT_LIBRARIES=ON in my cmake command hoping that might do it but no change unfortunately.

version layout:
Win 10
boost 1.63
openexr master
python 2.7.14

Was curious if anyone had any advice. TIA

**Comment by meshula** [comment]
Could you attach your CMakeCache.txt so we can get an idea of what your configuration looks like?

**Comment by cbdwtv** [comment]
Definitely! Here is said txt file.
[CMakeCache.txt](https://github.com/openexr/openexr/files/3789416/CMakeCache.txt)
Thanks

**Comment by meshula** [comment]
Your file indicates that CMake was able to find boost python, and python 2.7 but it wasn't able to determine specifically what version of python the boost python references. I wonder if our python detection logic does not detect the variant Rez provides?  @kdt3rd do you have any thoughts on what might be going on here? I'm having trouble deducing what constructs the string "PyImath_Python2_7"

**Comment by cbdwtv** [comment]
I am unsure if it is related but I still ran the ALL_BUILD and INSTALL vcxprojs and it seemed to build/install everything, until I tried using the result to compile alembic against and during that compile it said it was missing "PyIlmBaseConfigInternal.h" and sure enough that file was not in the resulting install dir of OpenEXR but was in its folder where cmake creates it (I assume).

**Comment by kdt3rd** [comment]
The config stuff is disabled based on a variable check, except that variable never set, so it will never generate the config files for PyIlmBase. This is left over from the old way of detecting whether or not python is available, where now we just return early and never run this code. I will submit a pull request shortly that will fix this.
