### ISSUE TITLE
Typo in generated IlmBase cmake config file

### ISSUE THREAD

**Issue by brainsandwich** [AcademySoftwareFoundation/openexr#621]
Hello,

There seem to be a typo in the generated IlmBaseConfig.cmake (when "installing" into a directory)

```cmake
set_target_properties(IlmBase::IlmThread PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_LINK_LIBRARIES "IlmBase::IlmBaseConfig;IlmBase::Iex;Threads::Threads" # <<< Issue here
)

if(CMAKE_VERSION VERSION_LESS 3.0.0)
  message(FATAL_ERROR "This file relies on consumers using CMake 3.0.0 or greater.")
endif()
```

The `INTERFACE_LINK_LIBRARIES` should contain `IlmBase::IlmThread` instead of `Threads::Threads`

* I had the issue on openexr-2.4.0, building with mingw64 on windows

**Comment by meshula** [comment]
For reference, there's a pull request working on sorting on pthread issues under mingw, here: https://github.com/AcademySoftwareFoundation/openexr/pull/591 --- however that resolves, it should include a solution for the IlmBaseConfig.cmake issue as well.

**Comment by cary-ilm** [comment]
@brainsandwich , are you suggesting that the set_target_properties of IlmBase::IlmThead should include IlmBase::IlmThread in the INTERFACE_LINK_LIBRARIES? @kdt3rd, does this sound right to you?

**Comment by brainsandwich** [comment]
@cary-ilm Oh I didn't see the target already was IlmBase::IlmThread ! My bad
It looks like CMake prevents such recursive definitions from breaking everything heh
So the solution should be to only remove Threads::Threads from INTERFACE_LINK_LIBRARIES, to prevent CMake from searching for a Threads::Threads target

**Comment by cary-ilm** [comment]
We discussed this in the steering committee meeting today, and we've lost track of exactly what the original problem is. Can you be more specific about the symptoms you're experiencing?

Also, we're planning to revamp the entire handling of threads and deprecate IlmThread altogether, for the 3.0 release later in the year.

**Comment by cary-ilm** [comment]
Revisiting this, is there any action to take here? As I mentioned, this is being complete overhauled for the 3.0 release. Closing the issue for now, but feel free to reopen if you'd like to continue the discussion.
