### ISSUE TITLE
Platform/OS dependent piz compressed binary data

### ISSUE THREAD

**Issue by arkellr** [AcademySoftwareFoundation/openexr#632]
Just pasting my commit comment which best describe this issue and fix. Will PR it shortly... but creating "an issue" for it first.

OpenEXR/IlmImf/ImfHuf.cpp: Fix OS dependent exr binary data for piz.
    
    Issue: piz compressed binary data was OS dependent e.g. different betw linux
    and osx. For example if one did a md5 checksum on the compressed data of an
    exr with identical image pixel/channel data it would return different checksums on linux and osx for the Piz compressor.
    
    This was due to the fact that the decoding huffman table stored, while having
    the same entries on linux and osx were sorted differently due to the differing
    behavior of STL heap sort for decode table entries that were equivalent.
    
    Fix was to simply update the heap compare operator to also handled this
    equality case.
    
    Updated: OpenEXR/IlmImfTest/testHuf.cpp to test for identical platform/os
    piz compressed exr file data blocks.

**Comment by cary-ilm** [comment]
@arkellr, were you going to submit a PR?

**Comment by cary-ilm** [comment]
Closing the issue since the PR is in, #637.
