### ISSUE TITLE
2.4.1: missing dist tar balls

### ISSUE THREAD

**Issue by kloczek** [AcademySoftwareFoundation/openexr#663]
Looks like there are missing dist tar balls for 2.4.1 IlmBase and OpenEXR on https://www.openexr.com/

Also to not rely on dist tar balls IMO it would be good to move IlmBase and OpenEXR to separate git repos (it will allow git autogenerate tar balls from git tag).

**Comment by cary-ilm** [comment]
Apologies, the downloads page on the website didn't get updated. We'll correct that.

But as of the 2.4 release, we're relying solely on the GitHub release mechanism, which doesn't bundle IlmBase and OpenEXR as separate tarballs.  Just download the entire repo and pull the subdirectory out of it.

And our plan is to move IlmBase into a separate git repo as of the planned 3.0 later in the year.

**Comment by kloczek** [comment]
This why I"ve suggested to put tjose projects as separated repos (just clone github.com/AcademySoftwareFoundation/openexr to IlmBase and OpenEXR 
and and remove in cloned repos files which shoulkd not be a part of the new splitted repos).
This would allow easier apply patches on top of the autogenerated tagged or release tar balls.

**Comment by kloczek** [comment]
IMO budling IlmBase and OpenEXR together does not make any sense.

On packaging it forces to packa in spource poackages stuff which is not needed.

**Comment by cary-ilm** [comment]
I've updated the downloads page on the website. As mentioned above, with the 3.0 release later this year, what was currently downloadable as independent tarballs will be split among separate GitHub repos.
