### ISSUE TITLE
autotools build not working in 2.4.0 or 2.4.1

### ISSUE THREAD

**Issue by dexterinbk** [AcademySoftwareFoundation/openexr#664]
According to instructions on buildpage, you switch into IlmBase run ./bootstrap, ./configure, make; make install.  Then cd into OpenEXR and run the same commands and it is supposed to build correctly.
For some reason the build for b44ExpLogTable is unable to find any of the shared libraries installed by IlmBase which pkg-config is listing as installed.  What changes do I have to make to kill this error?
*I cannot run cmake as the only version I have access to is too old to fulfill your requirements.

g++ -DHAVE_CONFIG_H -I. -I../config  -pthread -I/usr/local/include -I/usr/local/include/OpenEXR   -pthread -I.. -I../config    -pipe -g -O2 -std=c++14 -pthread -MT b44ExpLogTable.o -MD -MP -MF .deps/b44ExpLogTable.Tpo -c -o b44ExpLogTable.o b44ExpLogTable.cpp
mv -f .deps/b44ExpLogTable.Tpo .deps/b44ExpLogTable.Po
/bin/sh ../libtool  --tag=CXX   --mode=link g++ -pipe -g -O2 -std=c++14 -pthread   -o b44ExpLogTable b44ExpLogTable.o -L/usr/local/lib   -pthread -pthread -L/usr/local/lib -lImath-2_4 -lHalf-2_4 -lIex-2_4 -lIexMath-2_4 -lIlmThread-2_4   -lpthread  -pthread
libtool: link: g++ -pipe -g -O2 -std=c++14 -pthread -o b44ExpLogTable b44ExpLogTable.o -pthread -pthread -pthread  -L/usr/local/lib -lImath-2_4 -lHalf-2_4 -lIex-2_4 -lIexMath-2_4 -lIlmThread-2_4 -lpthread -pthread
/usr/bin/ld: cannot find -lImath-2_4
/usr/bin/ld: cannot find -lHalf-2_4
/usr/bin/ld: cannot find -lIex-2_4
/usr/bin/ld: cannot find -lIexMath-2_4
/usr/bin/ld: cannot find -lIlmThread-2_4
collect2: error: ld returned 1 exit status
make[1]: *** [b44ExpLogTable] Error 1
make[1]: Leaving directory `/root/openxr/openexr-2.4.1/OpenEXR/IlmImf'

**Comment by peterhillman** [comment]
Could you confirm that `/usr/local/lib` contains `libImath-2_4.so` `libImath.a`etc with timestamps consistent with your install?

If that looks good, the output from running configure would be helpful to see, particularly the lines after `checking for pkg-config...`

./configure can get mislead if the system already has an older version of IlmBase installed. You might try `export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig` before running the OpenEXR ./configure, though I think there may be a different issue here.

**Comment by dexterinbk** [comment]
I have no other version of IlmBase installed.  I did set PKG_CONFIG_PATH to /usr/local/lib/pkconfig before running the OpenEXR ./configure.  The only thing which worked was reverting to an earlier build of openexr: 2.3.0.  That builds with no issue.  Something broke in the autotools build in 2.4.0, which might not be a big deal for cmake advocates, but kills compilation for people using autotools.

**Comment by peterhillman** [comment]
I was able to build and install successfully from the v2.4.1 tag using configure/make/make install, so it isn't broken for everyone! (apparently I have autoconf version 2.59, automake 1.15.1)
You could perhaps try to narrow down which commit causes your issue?
It is often easier to identify issues by installing into a temporary location using the `--prefix` option to configure

**Comment by dexterinbk** [comment]
I am running this on the latest amazonlinux image, which may have outdated autotools....

**Comment by cary-ilm** [comment]
The problem may be related to the default install directory. Try specifying the install directory explicitly. This is the typical sequence that provides an explicit install directory:

cd $SRC_DIR/IlmBase
./bootstrap
./configure --prefix=$INSTALL_DIR
make install

cd $SRC_DIR/OpenEXR
./bootstrap
./configure --prefix=$INSTALL_DIR --with-ilmbase-prefix=$INSTALL_DIR
make 
make install

**Comment by cary-ilm** [comment]
Closing this issue for now. In the 2.5 release, the automatic generation of b44ExpLogTable has been deprecated, so the issue should have gone away entirely.
