### ISSUE TITLE
OpenEXR_Viewers  / libCg aliasing error

### ISSUE THREAD

**Issue by KBentley57** [AcademySoftwareFoundation/openexr#674]
I'm building openexr with externalproject_add as a third party library for my application.  I was using 2.3.0, and everything was working - including the viewers.  I install Nvidia_Cg in an earlier step, and now it appears that the viewer's CMake isn't working like it used to.  It appears that this effects both 2.4.0 and 2.4.1.

I'm getting the following error about aliasing imported libraries
```
NOTICE-- Found Cg library
CMake Error at OpenEXR_Viewers/config/LocateCg.cmake:18 (add_library):
  add_library cannot create ALIAS target "Cg::Cg" because target "Cg" is not
  a library.
Call Stack (most recent call first):
  OpenEXR_Viewers/CMakeLists.txt:51 (include)

CMake Error at OpenEXR_Viewers/config/LocateCg.cmake:30 (add_library):
  add_library cannot create ALIAS target "Cg::CgGL" because target "CgGL" is
  not a library.
Call Stack (most recent call first):
  OpenEXR_Viewers/CMakeLists.txt:51 (include)
```

I can see that libCg.so exists, and it finds it, but gets hung up here.

Thoughts?

**Comment by cary-ilm** [comment]
The OpenEXR_Viewer code is ancient and almost completely useless, it's not a functional viewer, it exists only as example code, but the dependencies are complicated and frequently problematic.

We discussed in the TSC and decided to remove the OpenEXR_Viewer code from the cmake build rules in the 2.5 release and then remove the code entirely in the 3.0 release, when the structure of the repo is rearranged.

**Comment by KBentley57** [comment]
@cary-ilm I had read that in some of the other commentary after submitting the report.  I'm not actually using my myself, but I was trying to build with all the available options turned on as a sanity check.  I hate to leave anything left to chance, but I'll turn it off for now and let it be if it's going to be removed down the road.

Thanks for the reply,

Kyle

**Comment by cary-ilm** [comment]
#676 removes OpenEXR_Viewers from the cmake build process, and removes references to it in the INSTALL instructions. The code will be retired in the 3.0 release later in the year.  This hopefully resolves the issue, closing for now.
