### ISSUE TITLE
Missing cmake option to install PyIlmBase pkg-config file for openexr-2.4.1

### ISSUE THREAD

**Issue by waebbl** [AcademySoftwareFoundation/openexr#678]
Although there exists a `PyIlmBase.pc.in` file in the PyIlmBase directory, there's no option for cmake to configure and install the file as there is for IlmBase.pc and OpenEXR.pc. I'm using the 2.4.1 tarball.

The attached patch adds this option accordingly. Feel free to use it if you like.

Additionally, I just noticed the installed pkg-config files might be not what they are meant to be. Take the `IlmBase.pc` file, for example. It looks like:
```
prefix=/usr
exec_prefix=bin
libdir=lib64
includedir=include
[...]
```

The pkg-config file of my installed ilmbase-2.3.0 looks like:
```
prefix=/usr
exec_prefix=${prefix}
libdir=/usr/lib64
includedir=${prefix}/include
[...]
```

All pkg-config files I've seen so far, have the `exec_prefix` variable like in the latter case and most have `${prefix}` prefixed for the value of at least the `includedir` variable, some also have it for the `libdir` variable, while others have it resolved like the `libdir` in the latter example above. But it's always an absolute and not a relative path.

[Add-option-to-install-PyIlmBase-pkg-config-file.patch.txt](https://github.com/AcademySoftwareFoundation/openexr/files/4278036/Add-option-to-install-PyIlmBase-pkg-config-file.patch.txt)

**Comment by kdt3rd** [comment]
sorry, you are right, there is no install for the python "libraries". When I did the cmake setup, those libraries appeared to be mostly private-ish and it was unclear if anyone would / should want to link against them, unless you were making your own version of the python bindings. But it is probably ok to expose this if that is helpful...

As to the prefix variables missing, this is annoying. You have to manually inject them to match the way pkg-config works vs cmake install. If you look at the IlmBase version of this, in IlmBase/config/CMakeLists.txt, we have `set(include "\${prefix}/${CMAKE_INSTALL_INCLUDEDIR}")` which will end up in the file as `${prefix}/include` (or whatever you had the cmake variable at). This is working fine for me, I end up with an IlmBase.pc which has the variable references in exec_prefix, libdir, includedir, etc.

So this is not working for you? I noticed you didn't have the above in your PyIlmBase patch...

**Comment by waebbl** [comment]
Thanks for your reply. The reason why I haven't added this to my PyIlmBase patch was, because it's not added in the tarball sources for IlmBase either. I just copied the code from the IlmBase or OpenEXR config/CMakeLists.txt, removing the part about pthread, which seems not be needed according the PyIlmBase.pc.in file.

The changes you mention were introduced in commit 0b26a9dedda4924841323677f1ce0bce37bfbeb4 on Nov 5, but apparently they seem to not have found their way into the RB-2.4 branch which looks like the base for the 2.4.1 tarball I was using (c.f. https://github.com/AcademySoftwareFoundation/openexr/blob/RB-2.4/IlmBase/config/CMakeLists.txt#L74 and https://github.com/AcademySoftwareFoundation/openexr/releases)

**Comment by meshula** [comment]
How would this affect our plans to move to pybind11? If we publish boost-linked bindings, have we created a community expectation of ongoing link compatibility with boost python?

**Comment by kdt3rd** [comment]
@waebbl - right you are! There were a few changes we waffled on from master when making the 2.4.1 release, I guess the fix you mention did not get merged over, it should, sorry for the confusion.

@meshula - these dsos are necessary currently, although I am still skeptical that they need to be publicly linkable. Although I don't know for sure - if you are making your own python bindings which use ilmbase in some way, then most likely. The pybind11 work may not change that much, as I remember there was some issue with the exceptions and needing to have one singleton-ish copy of something being instantiated. I don't know if that was specific to boost python however, or at the moment, what the specific issue was. But when I did the cmake rewrite, I ran into this and had to add them back (I had initially tried to just put all the code directly in the python extension). However, I don't think anyone will fault us for switching away from boost python, they may even send cake.

**Comment by meshula** [comment]
Boost python does indeed have a global shared dictionary, although the details escape me at the moment. ILM internally has had code that linked against boost::python details within these bindings; I don't know if that's a concern to them anymore... @cary-ilm ? 

To the point, I'm not objecting to publishing, just wanting to triple-check we aren't painting into a boost::python corner.

**Comment by maxnbk** [comment]
This could turn out to be marginally related as well:
#725

**Comment by cary-ilm** [comment]
Closing this as PR #681 went into the 2.5.0 release, feel free to re-open or file another issue if necessary.
