### ISSUE TITLE
CMake picks wrong python version

### ISSUE THREAD

**Issue by freder** [AcademySoftwareFoundation/openexr#684]
despite me specifying the python3 version I want to use, cmake seems to only want to use the one that comes with xcode, for some reason.

before _configure_:
<img width="1280" alt="Screenshot 2020-03-09 at 22 48 50" src="https://user-images.githubusercontent.com/724844/76260542-4e635c00-6258-11ea-8ece-c681e7820fb9.png">

after:
<img width="1280" alt="Screenshot 2020-03-09 at 22 49 18" src="https://user-images.githubusercontent.com/724844/76260554-5a4f1e00-6258-11ea-8957-afc0593619f1.png">

am I missing anything here?

**Comment by hodoulp** [comment]
We face the same issue with OCIO when build with the latest OpenEXR version i.e. Python 3 installed but there is a mismatch between boost & PyIlmBase & Python:
```
-- Configure PyIlmBase Version: 2.4.0 Lib API: 24.0.2
-- Found Python: /usr/local/bin/python3.7 (found version "3.7.3") found components:  Interpreter Development 
-- Could NOT find Python2 (missing: Python2_LIBRARY Python2_INCLUDE_DIR Development) (found version "2.7.5")
-- Found Python3: /usr/local/bin/python3.7 (found version "3.7.3") found components:  Interpreter Development 
: Found Python 3.7.3
-- Found Python3 libraries: 37
-- Found Boost 1.70.0 at /usr/local/lib/cmake/Boost-1.70.0
--   Requested configuration: QUIET OPTIONAL_COMPONENTS python;python2;python3;python37
-- Found boost_headers 1.70.0 at /usr/local/lib/cmake/boost_headers-1.70.0
-- Found boost_python 1.70.0 at /usr/local/lib/cmake/boost_python-1.70.0
--   libboost_python37.so.1.70.0
-- Adding boost_python dependencies: headers
-- Found Boost: /usr/local/lib/cmake/Boost-1.70.0/BoostConfig.cmake (found version "1.70.0") found components:  python missing components:  python2 python3 python37
CMake Warning at PyIlmBase/CMakeLists.txt:104 (message):
  Ambiguous boost python module found, assuming python 2


CMake Warning at PyIlmBase/config/NumPyLocate.cmake:14 (message):
  Unable to import numpy using python 2.7.5
Call Stack (most recent call first):
  PyIlmBase/CMakeLists.txt:133 (include)
```

**Comment by meshula** [comment]
I just verified that there is a Python3 embedded in Xcode on my machine as well; I was not aware of that, and it explains some odd behavior I am getting in a number of Python related projects. Looking at all those pythons referenced in your cmake-gui, I am guessing that you want the miniconda copy of python? That is a LOT of Pythons on your machine :\ I see Pythons from the system, Xcode, miniconda, and both py2 and 3 installed by brew.

I notice cmake 3.17 has been released since you posted, and it includes new logic to detect pythons in conda (hopefully that includes miniconda!), so maybe an avenue of attack is to upgrade to cmake 3.17, delete your build directory, and try configuring clean?

Also, cmake has a new rule that variables named MYLIB_LIBRARY are for user specified library override, and variables named MYLIB_LIBRARIES are for libraries discovered by the find_package utility. Maybe you specified your python with PYTHON_LIBRARIES?

**Comment by zachlewis** [comment]
I've been having similar trouble, so I spent some time digging in to this today.

Note: everything below pertains to the master branch, as it exists today; notably, this doesn't seem to work (for me) with the v2.4.1 branch.

I found that I was able to get things working with cmake 3.17 by specifying the path to the interpreter(s) with the "**PythonX_EXECUTABLE**" cmake variables, where X is 2 or 3, accordingly (e.g., cmake -DPython3_EXECUTABLE=/path/to/python3/bin/python3)

(In theory, just setting Python_EXECUTABLE should work, but I found that if CMake can find a later (minor?) version of Python, it uses that instead. There's a "Python_FIND_STRATEGY" hint that's supposed to help control for which of multiple found versions CMake selects, but I couldn't get it to behave properly)

Patrick, you may need to additionally provide a "**Boost_PYTHON_LIBRARY**" value, e.g. cmake -DBoost_PYTHON_LIBRARY=3.7m ...

Also, I'm not sure if this is related, but the only way I could control for the install location of the compiled python modules was by pointing a $PYTHONUSERBASE environment variable to my destination prefix, which forces imath.so and iex.so to install to ${prefix}/lib/pythonx.x/site-packages, as expected (by me, anyway). Without providing $PYTHONUSERBASE, the modules seem to end up in the default user site-packages location configured for the specified python interpreter. Not sure what the behavior is when installing with root permissions.


Hope this is helpful!

Ref: https://cmake.org/cmake/help/v3.17/module/FindPython.html

**Comment by kdt3rd** [comment]
Yes, we are not doing anything custom to find python - we use the cmake python find, with the only wrinkle that we look for python, python2, and python3 in an attempt to handle py 2 & 3 at the same time, and then fall back to a default python. So any cmake options to control that search will be what is needed to find a particular version.

After that, the install locations and such should be queried either by asking the interpreter or other files in the found version, and so with this, I believe we are correctly deferring to what cmake determines, but if this isn't working and you can't set cmake appropriately, please let us know.

**Comment by cary-ilm** [comment]
Following up, is this resolved? OK to close for now?

**Comment by cary-ilm** [comment]
Closing for now, but feel free to reopen if you'd like to continue the discussin.

**Comment by ghost** [comment]
I recently faced the same issue in another project
the solution was to specify the desired Python version and using "EXACT" when using find_package
`find_package(Python "3.11" EXACT COMPONENTS Development.Module)`
