### ISSUE TITLE
ZLIB not found

### ISSUE THREAD

**Issue by gpiffaretti** [AcademySoftwareFoundation/openexr#687]
I guess this is a question more than an issue, but I don't know where to go for a solution.
What does it mean to have ZLIB installed? Do I need to have a static or dynamic library somewhere? How is CMake supposed to find it? CMake is not finding it so I'm unable to compile.
Some people claim to have that same problem.
I really appreciate any help you guys can give me.

Thanks
Gonzalo

**Comment by meshula** [comment]
> How is CMake supposed to find it?

It's expected to be available on the system search path ~ what this means per platform is different; and it's usually already on the system path on linux and macos. 

It would be helpful to have some more information, such as what platform you are compiling for, and what command line you used to initiate cmake configuration.

**Comment by gpiffaretti** [comment]
I was using Windows. I was able to solve it but I didn't really understand what happened. I used a script I found online that downloaded zlib and copied it somewhere else and that worked.

**Comment by cary-ilm** [comment]
It seems this issue is resolved, so I'll close for now. If you need further assistance, feel free to re-open or file a new issue.
