### ISSUE TITLE
Compilation errors on ImfScanLineInputFile.cpp with GCC 5.5.0

### ISSUE THREAD

**Issue by gdsotirov** [AcademySoftwareFoundation/openexr#706]
As I was trying to build [OpenEXR 2.2.2](https://github.com/AcademySoftwareFoundation/openexr/releases/tag/v2.2.2) on Slackware 14.2 I encountered the following compilation issues:

```
...
Making all in IlmImf
make[1]: Entering directory '/usr/src/tmp/openexr-2.2.2/OpenEXR/IlmImf'
make  all-am
make[2]: Entering directory '/usr/src/tmp/openexr-2.2.2/OpenEXR/IlmImf'
/bin/sh ../libtool  --tag=CXX   --mode=compile i586-slackware-linux-g++ -DHAVE_CONFIG_H -I. -I../config -pthread -I/usr/include/OpenEXR -I.. -I../config   -pipe -O3 -march=i586 -mtune=i686 -MT ImfScanLineInputFile.lo -MD -MP -MF .deps/ImfScanLineInputFile.Tpo -c -o ImfScanLineInputFile.lo ImfScanLineInputFile.cpp
libtool: compile:  i586-slackware-linux-g++ -DHAVE_CONFIG_H -I. -I../config -pthread -I/usr/include/OpenEXR -I.. -I../config -pipe -O3 -march=i586 -mtune=i686 -MT ImfScanLineInputFile.lo -MD -MP -MF .deps/ImfScanLineInputFile.Tpo -c ImfScanLineInputFile.cpp  -fPIC -DPIC -o .libs/ImfScanLineInputFile.o
ImfScanLineInputFile.cpp: In constructor 'Imf_2_2::ScanLineInputFile::ScanLineInputFile(Imf_2_2::InputPartData*)':
ImfScanLineInputFile.cpp:1176:50: error: 'nullptr' was not declared in this scope
                    _data->lineBuffers[i]->buffer=nullptr;
                                                  ^
ImfScanLineInputFile.cpp: In constructor 'Imf_2_2::ScanLineInputFile::ScanLineInputFile(const Imf_2_2::Header&, Imf_2_2::IStream*, int)':
ImfScanLineInputFile.cpp:1234:50: error: 'nullptr' was not declared in this scope
                    _data->lineBuffers[i]->buffer=nullptr;
                                                  ^
Makefile:796: recipe for target 'ImfScanLineInputFile.lo' failed
...
```

This is because [Slackware 14.2](http://www.slackware.com/) is old (released 2016-07-01) and comes bundled with old GCC (5.5.0). However, it's enough to just add option `-std=c++11` on compiler's command line to fix the problem.

I think adding this option in the build script won't do any harm and would clearly indicate the required C++ standard support, because after all _null pointer constant_ (i.e. `nullptr`) is a [C++11 feature](https://gcc.gnu.org/projects/cxx-status.html#cxx11). So would you consider the following patch for [openexr/blob/master/OpenEXR/IlmImf/Makefile.am](https://github.com/AcademySoftwareFoundation/openexr/blob/v2.2.2/OpenEXR/IlmImf/Makefile.am)?

```diff
-INCLUDES = @ILMBASE_CXXFLAGS@ \
+INCLUDES = @ILMBASE_CXXFLAGS@ -std=c++11 \
 	   -I$(top_builddir)  \
 	   -I$(top_srcdir)/config
```

I'm also open to other options, because I'd like to stick to OpenEXR 2.2.x series until Slackware 15 is released (no official date set yet), so I build 2.4.x for it.

**Comment by cary-ilm** [comment]
Apologies for this, it looks like some of the recent C++11-isms leaked into the backport. It might be fine to add the -std=c++11 option, although that flag can also be provided as an argument to the "configure" script. Would that suffice for you?  I can make the patch, but I'd prefer to do that only if it's truly necessary.

**Comment by gdsotirov** [comment]
Yes, it's from the back port of the CVE fixes. Adding the flag to the `configure` script is of course an option, but it's a less obvious one IMHO and won't fix it for others. Anyway, the issue describes the problem and the solution, so no need to patch anything.
