### ISSUE TITLE
PyIlmBaseConfigInternal.h referenced, missing from install payloads (CMake)

### ISSUE THREAD

**Issue by zachlewis** [AcademySoftwareFoundation/openexr#710]
It seems PyImathFixedArray.h and PyImathMathExc.h are looking for PyIlmBaseConfigInternal.h, which doesn't seem to make it into the install payload when using CMake (i.e., from the openexr root directory). Not sure what happens with autoconf. 

OpenEXR / IlmBase / PyIlmBase libraries all seem to compile, link, and otherwise behave just fine from what I can tell... but I'm experiencing a fatal error building PyAlembic (specifically, when PyIArrayProperty.cpp tries to include PyImathFixedArray.h, which in turn tries to include PyIlmBaseConfigIternal.h). 

I'd be happy to provide my rez build scripts if that would be helpful...!

**Comment by cary-ilm** [comment]
You are correct. The autoconf build is erroneously installing this header, it should not be distributed. I submitted a fix, #712, which removes the #include from all public headers. please check it out.

Currently, the only thing PyIlmBaseConfigInternal.h has is the PYIMATH_ENABLE_EXCEPTIONS symbol.

**Comment by zachlewis** [comment]
Cary, you've done it again. 
Thanks so much! #712 does exactly what it should, and everything's gravy. I appreciate your prompt response!
