### ISSUE TITLE
compressVerify fails on ARM

### ISSUE THREAD

**Issue by mbakke** [AcademySoftwareFoundation/openexr#713]
compressVerify from testHuf.cpp fails on ARMv7 and AAarch64:

```
verifying compressed checksum hash = 2013380646
IlmImfTest: /tmp/guix-build-openexr-2.5.0.drv-0/openexr-2.5.0-checkout/OpenEXR/IlmImfTest/testHuf.cpp:213: void {anonymous}::compressVerify(const short unsigned int*, int, unsigned int): Assertion `compressedHash == dekHash' failed.
```

**Comment by peterhillman** [comment]
@arkellr do you have an opinion on this
PR #717 has a proposed fix. The issue appears to be that on the ARM, 8 bit signed values are not sign-extended when converting to 32 bit unsigned, but on x86 that does happen. The change should force all architectures to work the same way as the ARM, which might have been what is intended. The precomputed checksums have been updated to the new values.
It might also be possible to update the code so the ARM works the same way as the x86, but I don't know the best approach.

None of this effects the core operation of the library itself: the data was being compressed identically, it's only the test itself that was erroneously reporting an issue

**Comment by arkellr** [comment]
That PR change looks reasonable.
The explicit “unsigned char” cast should ensure predictable behavior across archs.
Yes the intent was that checksum routine (i grabbed it from Knuths book) produce the same chksum across archs.

**Comment by arkellr** [comment]
btw... ‘cptr’ could  be ‘const unsigned char *’ ie. 

const unsigned char* cptr = reinterpret_cast<const unsigned char*>(uncompressed);

... which saves on hvin to cast in the loop?

**Comment by peterhillman** [comment]
I've updated the PR as suggested. It's slightly messier because it needs to go through the user-defined conversion `operator()` from Array to const char* first.

**Comment by arkellr** [comment]
awesome... thx for figuring it out.
btw not sure how feasible... but might be good if the jenkins ci did an ARM pass at some point.

**Comment by peterhillman** [comment]
It would be good to have a CI test for ARM, though it took my raspberry pi more than five hours to run the full IlmImfTest, so it might not be possible to do that very often.

OpenEXR is built for a lot of different processors and OSes, more than could be supported by a single CI.  Perhaps folks who regularly build for more unusual systems do frequent build and tests of the master branch between releases. Flagging up any issues caused by the latest commits would mean they could be addressed before the next release.
