### ISSUE TITLE
Remove deprecated argument to getChunkOffsetTableSize

### ISSUE THREAD

**Issue by peterhillman** [AcademySoftwareFoundation/openexr#740]
In 2.5.1 and earlier, `getChunkOffsetTableSize` had a parameter to control whether it used the `chunkCount` attribute to compute the size of the table, or derived it from other attributes. With PR #738, `getChunkOffsetTableSize` always derives it if possible, falling back to `chunkCount` only for unknown types. This prevents errors if `chunkCount` is somehow incorrect, with an insignificant extra overhead. `chunkCount` now only exists to allow future types to be added but still be partially readable by older versions of the library.

The parameter in `getChunkOffsetTableSize` still exists, to prevent ABI and API incompatibilities. At the next API change it should be removed entirely.

**Comment by cary-ilm** [comment]
Now is a good time to address this, with a major release coming soon.

**Comment by cary-ilm** [comment]
Addressed by #988.
