### ISSUE TITLE
[CMake] Symlinks under Windows

### ISSUE THREAD

**Issue by OgreTransporter** [AcademySoftwareFoundation/openexr#741]
Creating symbolic links during installation does not work on Windows. Example:
```
EXEC : CMake error : failed to create symbolic link 'Imath.dll': operation not permitted
```
It is useless anyway, because when distributing the DLLs to other systems the links do not work anymore. The links have to be recreated on each system. This must then be integrated into the installation program.

See #739

**Comment by OgreTransporter** [comment]
See issue #741 and  #739

**Comment by cary-ilm** [comment]
OK to close this, since #742 has been merged?

**Comment by cary-ilm** [comment]
Closing this, assuming it's resolved, feel free to reopen if not.
