### ISSUE TITLE
Cmake overriding find_package

### ISSUE THREAD

**Issue by petersteneteg** [AcademySoftwareFoundation/openexr#752]
In 
https://github.com/AcademySoftwareFoundation/openexr/blob/2600cdc0302cd0779cc5129ec6f43ec5c3c59926/CMakeLists.txt#L28-L36
You override find_package, that is not supported officially by cmake and might be removed in future versions, and one can only do so once, hence if there are more than one project doing it in the same build it will fail. 

A better solution is to have your subproject create a "dummy" FindFoo.cmake and put that in a directory at the beginning of the CMAKE_MODULE_PATH, then that dummy package will get found by the find_package(Foo) and then target_link_libraries will work as normally. 

I can provide a PR if you want.

**Comment by meshula** [comment]
A PR would be nice to see, thanks!

**Comment by cary-ilm** [comment]
Closing, as this seems to have been addressed by  #775.
