### ISSUE TITLE
python version for openexr

### ISSUE THREAD

**Issue by ZFaniso** [AcademySoftwareFoundation/openexr#753]
Hi i'm currently starting to use openexr to view my rendered models. i enconter problems while installing the openexr .
First i'm runningit on linux 20.04 with python3.

I followed the below instructions:
I cloned the repository  using the command line -git clone 1. https://github.com/AcademySoftwareFoundation/openexr.git
2. I followed the installation procedure such  where i created build_directory, while i'm inside the build directory i took the source file (cloned openexr)inside the directory, then i ran cmake openexr. I
 got an error which says -Found Python: /usr/bin/python3.8 (found version "3.8.2") found components: Interpreter Development 
-- Could NOT find Python2 (missing: Python2_LIBRARIES Python2_INCLUDE_DIRS Development) (found version "2.7.18")
-- Found Python3: /usr/bin/python3.8 (found version "3.8.2") found components: Interpreter Development 
CMake Warning at PyIlmBase/CMakeLists.txt:54 (message):
  : Unable to find Python2 interpreter or development libraries

-- : Found Python 3.8.2
-- Found Python3 libraries: 38
--   -> Will install to: lib/python3/dist-packages
-- Disabling boost-provided cmake config. If this causes problems, consider setting Boost_NO_BOOST_CMAKE variable to OFF
-- Could NOT find Boost (missing: Boost_INCLUDE_DIR) 
CMake Warning at PyIlmBase/CMakeLists.txt:184 (message):
  Unable to find boost::python library, disabling PyIlmBase.  If you believe
  this is wrong, check the cmake documentation and see if you need to set
  Boost_ROOT or Boost_NO_BOOST_CMAKE

-- clang-format not found.
-- Configuring done
-- Generating done
-- Build files have been written to: /home/zimbini/build_directory

so my question is does python run in python2?
or is there something that i did wronge while installing openexr.

**Comment by meshula** [comment]
It seems that cmake is unable to find your installation of boost python. Perhaps you can start by double checking that you've installed a copy of boost python that matches the version of python you wish to use.

**Comment by ZFaniso** [comment]
ok let me try that  thanks meshula

**Comment by cary-ilm** [comment]
Is this still an issue? Based on your first comment that you're using OpenEXR to view rendered image, do you even need the python bindings? Could you just disable the building of PyIlmBase altogether and avoid the issue entirely?

**Comment by cary-ilm** [comment]
Closing for now, but feel free to reopen or file a new issue if you need further assistance.
