### ISSUE TITLE
OPENEXR_PACKAGE_STRING mangled

### ISSUE THREAD

**Issue by lgritz** [AcademySoftwareFoundation/openexr#754]
`OPENEXR_PACKAGE_STRING` should be defined in OpenEXRConfig.h as "OpenEXR x.y.z"

Seems to be (at least in 2.4 and 2.5): "IlmBase "

Weird!

In IlmBaseConfig.h, ILMBASE_PACKAGE_STRING is correct: "IlmBase 2.5.1" (for example). So at least that one is correct.

**Comment by cary-ilm** [comment]
Fixed by #755
