### ISSUE TITLE
staticInitialize to get a staticDeInitialize equivalent

### ISSUE THREAD

**Issue by mrvux** [AcademySoftwareFoundation/openexr#765]
Hello,

I'm currently integrating openexr in one of our projects, everything works well, but the call to staticInitialize in ImfHeader does create a static typeMap and is is never cleaned.

Since we use visual leak detector we have a lot of small leaks report on application exit. 

It would be nice to have the equivalent :

    staticDeInitialize

That unregisters all the types

It is possible to deinit types by calling unRegisterAttributeType, but there is still the type map pointer that is still not deleted

    static LockedTypeMap* tMap;

So staticDeInitialize should also take care of deleting the  static type map pointer in ImfAttribute

This requires a few changes (moving statics and lock outside of the functions mostly), and the call can still be optional (so user can decide between a clean exit or letting OS to do it for him.

I'm absolutely happy to submit this as a Pull request.

Thanks

Julien

**Comment by peterhillman** [comment]
Hi Julien, which version of OpenEXR do you have? `tMap` was changed to a non-pointer in OpenEXR-2.3.0, which should make the staticDeInitialize unnecessary, as it should clean up automatically. I now get clean reports from every leak detector I've tried.

**Comment by mrvux** [comment]
Hello, we are using version 2.4.2, and running on a windows build (linking as static libraries)

this likely comes from this then

#if __cplusplus >= 201103L
    static LockedTypeMap tMap;
    return tMap;

In visual studio (2019) it still uses the pointer version (__cplusplus maps to 199711L)

**Comment by lgritz** [comment]
In 2.5+ (and 2.4? I can't remember now) we advertised a minimum of C++11, so these `#if` guards can all be eliminated. We don't need to support C++ < 11 at all.

**Comment by meshula** [comment]
Not to mention that the __cplusplus  if guards have been broken for a decade(?!) on msvc!

**Comment by peterhillman** [comment]
The if guards have been removed for the 2.5 release by @meshula, so hopefully using v2.5.2 should fix the problem.

**Comment by cary-ilm** [comment]
Closing this issue, as it seems to have been resolved, at least in the 2.5 release.
