### ISSUE TITLE
Those .cvsignore repo files. Do we still need them?

### ISSUE THREAD

**Issue by arkellr** [AcademySoftwareFoundation/openexr#767]
Housing keeping PR. :)
The repo still retains .cvsignore files within each project folder.
Im guessing these were carried forward from the cvs repo/autoconf days (savannah days).
So my question... do we still need them since the repo is in github and we are using cmake to build (much of the .cvsignore entries seem to be build byproducts of autoconf).
I'd vote to clean em up if these files are unused.

Let me know.

find . -name ".cvsignore" -print
./IlmBase/IlmThread/.cvsignore
./IlmBase/Imath/.cvsignore
./IlmBase/ImathTest/.cvsignore
./IlmBase/IexTest/.cvsignore
./IlmBase/Half/.cvsignore
./IlmBase/HalfTest/.cvsignore
./IlmBase/Iex/.cvsignore
./IlmBase/.cvsignore
./OpenEXR_Viewers/playexr/.cvsignore
./OpenEXR_Viewers/exrdisplay/.cvsignore
./OpenEXR_Viewers/doc/.cvsignore
./OpenEXR_Viewers/.cvsignore
./OpenEXR/IlmImf/.cvsignore
./OpenEXR/exrmaketiled/.cvsignore
./OpenEXR/IlmImfExamples/.cvsignore
./OpenEXR/exrmakepreview/.cvsignore
./OpenEXR/exrstdattr/.cvsignore
./OpenEXR/doc/.cvsignore
./OpenEXR/IlmImfTest/.cvsignore
./OpenEXR/exrenvmap/.cvsignore
./OpenEXR/exrheader/.cvsignore
./OpenEXR/.cvsignore

**Comment by meshula** [comment]
It looks like our .gitignore at the root has all the same things covered, so I can't think of any reason to keep the .cvsignore files, not even for reference.

**Comment by cary-ilm** [comment]
Yes, they can surely go!

**Comment by arkellr** [comment]
Right-O thx for checking.

PR here...
https://github.com/AcademySoftwareFoundation/openexr/pull/769

**Comment by cary-ilm** [comment]
PR #769 is merged, so closing.
