### ISSUE TITLE
Win32 cmake trying to use pthread?

### ISSUE THREAD

**Issue by zezba9000** [AcademySoftwareFoundation/openexr#781]
When I run "cmake ..\" first error I get is "-- Looking for pthread.h - not found".

Why is it trying to use pthread on Win32?

Unless I missed it, I don't see anything in the build docs on this.

Win10 x64
VS 2019
openexr 2.5.2

**Comment by zezba9000** [comment]
Or is there pre-build binaries for Win32?

**Comment by meshula** [comment]
It might be possible to download builds from the CI, but perhaps someone else can comment on that.

The error you are seeing is not an error, it's just imformative. It happens with CMake builds in general. It's not trying to use pthreads or requiring it, it is checking if pthreads exist or not. The case where it exists is when you are building for linux, or when you are building for windows under mingw. In your case, pthreads will not be used, which is what you are expecting, I think.

Have you encountered a build failure after that?

**Comment by zezba9000** [comment]
I ended up just using TinyEXR as it just compiles without going down a rabbit hole of dependencies and does what I need.
Why are there no pre-compiled binaries for OpenEXR or at min pre-compiled dependencies for projects like these baffles me.

When you're just trying to extend a small tool app these things take up more time than the app itself sometimes & I have to many things to do.

**Comment by lgritz** [comment]
This project doesn't build and host binaries on our own, but there are multiple pre-built binaries out there (or one-step build from source including dependencies), for all kinds of systems.

On Windows, Vcpkg is super easy to build from source including dependencies. There are also Nuget and Chocolatey pre-built, though I find those difficult to ascertain which are most complete and up to date, as they lack a single official or definitive distribution of packages. A simple web search reveals other people hosting pre-built binaries of various versions, such as https://github.com/mkturkcan/Precompiled-OPENEXR-ILMBASE-for-Windows and probably many others.

Homebrew or Macports for Mac is both complete and reasonably up to date (2.5 and 2.3, respectively).

Most Linux distributions have pre-built packages for openexr using their default package managers.

Both Conan and Conda are available on multiple platforms as built-from-source options (both up to date with 2.5).

There are so many options for prebuilt or auto-build-from-source, it's not even clear how we would make things better or more complete by doing it ourselves.
