### ISSUE TITLE
Static build on Windows broken?

### ISSUE THREAD

**Issue by mabuware** [AcademySoftwareFoundation/openexr#833]
building on windows, it seems OPENEXR_DLL gets defined in any case.

I had to remove these lines to make the static build work:

https://github.com/MrMabulous/openexr/commit/c5e8761064437989ab0e4fc7dd3cd44dc2f6a5c0

But I assume there is some purpose to these lines, so I'm not sure if that breaks something else.

**Comment by meshula** [comment]
You're right, that bit of code is ignoring the static/dynamic option.

**Comment by meshula** [comment]
resolved by https://github.com/AcademySoftwareFoundation/openexr/commit/ec8af9a541b12e50f7fb7ac8ef99f348ada9bb1c
