### ISSUE TITLE
name

### ISSUE THREAD

**Issue by adammaj1** [AcademySoftwareFoundation/openexr#879]
what means name of the libray :Ilmimf ?
ilm stands for Industrial Light & Magic (ILM)
what about imf?

**Comment by lgritz** [comment]
Image format.

The name is changing, in OpenEXR 3.x, the library will be libOpenEXR.

This is not really an "issue" as we typically use this feature. We tend to use GitHub issues to report bugs or track feature requests. For just a casual question, it is much easier to just ask it on the openexr mail list.

**Comment by adammaj1** [comment]
Sorry for misuse and thx for the explanation : 
https://stackoverflow.com/questions/27502723/where-i-can-find-libopenexr-so-in-ubuntu
https://en.wikipedia.org/wiki/OpenEXR#parts

**Comment by lgritz** [comment]
@adammaj1 I think you put an embarrassing typo in the library name in your Wikipedia edit.

**Comment by peterhillman** [comment]
Also, a 'part' has a special meaning within OpenEXR (From version 2.0 onwards, channels of OpenEXR images can be spread across multiple _parts_ to allow them to be read independently or stored using different schema)

**Comment by lgritz** [comment]
~~GitHub needs a "huh?" reaction for when you think a comment may have gotten sent to the wrong conversation.~~
Oh, no, never mind, it's me who didn't understand!

**Comment by adammaj1** [comment]
@lgritz Where is the typo ? ( I was looking for it )

**Comment by adammaj1** [comment]
@peterhillman I have change part to 
https://en.wikipedia.org/wiki/OpenEXR#distribution

Is it OK now?

**Comment by lgritz** [comment]
> @lgritz Where is the typo ? ( I was looking for it )

IlmImf versus ilmilf

**Comment by adammaj1** [comment]
@lgritz Thx. I hope that it is OK now ( ?)

**Comment by lgritz** [comment]
Spelling is correct now, but I would encourage you to fix the capitalization, since most file systems are case-sensitive.

**Comment by adammaj1** [comment]
@lgritz Yes. You are right. The reason why I used all small letters that now in wikipedia big I looks the same as small l, It is hard to read /spell the name of the library
