### ISSUE TITLE
Various issues integrating OpenEXR as a CMake subproject

### ISSUE THREAD

**Issue by Anteru** [AcademySoftwareFoundation/openexr#881]
This is a (unsorted) list of problems I ran into when trying to use OpenEXR as a submodule within a bigger project. It would be great if those get addressed, as it would make consuming OpenEXR _much_ easier.

* Please don't write messages unless it's an error. By default, I'm seeing:
  ```
   Configure ILMBASE Version: 2.5.3 Lib API: 25.0.2
   -- WARNING pkg-config generation disabled
   Configure OpenEXR Version: 2.5.3 Lib API: 25.0.2
   ```
  This happens on every single configuration. That quickly adds up when every project does it.
* Please don't set `BUILD_SHARED_LIBS` if you're not the top-level project. An easy check is to compare the `CMAKE_CURRENT_SOURCE_DIR` with `CMAKE_SOURCE_DIR` and not turn on global options if it's a submodule. Instead, please add a prefixed option like `OPENEXR_BUILD_SHARED` or similar. That should be fairly easy to use given `ILMBASE_DEFINE_LIBRARY` is the entry point for library definitions, and you can simply select the library type there:
  ```
    if(OPENEXR_BUILD_SHARED_LIBS)
      set(OPENEXR_LIB_TYPE SHARED)
    else()
      set(OPENEXR_LIB_TYPE STATIC)
    endif()
    add_library(${objlib} ${OPENEXR_LIB_TYPE}
      ${ILMBASE_CURLIB_HEADERS}
      ${ILMBASE_CURLIB_SOURCES})
  ```
  I think that requires getting rid of the dual shared/static build as well.
* It would be nice if `PyIlmBase` was disabled by default, or at least fail _silently_, at the moment it produces a lot of debug output (i.e. could not find Python2, but did find Python3, and fail eventually because Boost.Python is missing ...). Not a dealbreaker, as there is an option to disable it, but it would be nice if it got disabled automatically if the dependencies can't be satisfied.
* It would be great if all options are prefixed `OPENEXR_` consistently -- there are various prefixes used here (`PYILMBASE_` for example).
* Don't add CDashBoard targets unconditionally when built as a submodule (this can be worked around by setting `BUILD_TESTING` to off -- would be nice to have it off by default for submodules though.)
* Don't install by default -- this requires all dependencies to be export-able, so for instance if I statically compile ZLIB and IlmImf in my "superproject", then my ZLIB needs to be exportable to satisfy IlmImf's export statement, even though I don't want to install ZLIB or IlmImf. Would be great if this was an option.

**Comment by meshula** [comment]
Thanks for these detailed notes. They touch on a number of other open issues. I broke down individual issues to track the problems raised, and to relate the individual issues to pre-existing issues. The individual sub-issues should make it easier to discuss and make progress incrementally.

I didn't reference the PyIlmbase issue in the sub-issues, it's resolved in the Imath project.

**Comment by meshula** [comment]
zlib referencing is controlled by OPENEXR_FORCE_INTERNAL_ZLIB
We no longer build static and shared together
a pass has been done on conforming on OPENEXR_*
NOTICE has been changed to STATUS, WARNING, FATAL_ERROR as appropriate.

If any of these could use more work, please let us know in this issue, or a new one! Thanks again for the feedback.

**Comment by Anteru** [comment]
Thanks, this is looking good! Minor nitpicks only:

* If you could use `if(NOT TARGET ZLIB::ZLIB)` to check if ZLIB is present before calling `find_package(zlib)`, that would make integration a bit easier. I made this change locally:
  ```
  if (NOT OPENEXR_FORCE_INTERNAL_ZLIB)
    if(NOT TARGET ZLIB::ZLIB)
      find_package(ZLIB QUIET)
    endif()
  endif()
  if(OPENEXR_FORCE_INTERNAL_ZLIB OR NOT TARGET ZLIB::ZLIB)
  ```
  in `OpenEXRSetup.cmake`.
* It still tries to install by default, which causes failures if my own copy of ZLIB is not exported. Removing the last `INSTALL` statement from `openxr/cmake/CMakeLists.txt` fixes it
* I see a bit of debug spew on each configure:

  ```
  Configure Imath Version: 3.0.0 Lib API: 26.0.0
  Imath is configuring as a cmake sub project
  pkg-config generation disabled
  Configure OpenEXR Version: 2.5.99 Lib API: 26.0.1
  OpenEXR is configuring as a cmake subproject
  -- pkg-config generation disabled
  ```

With those changes applied I got OpenEXR to work locally, without any of the previous pain :) Thanks a lot for that!

Is this ok keeping here or do you want me to file a new issue?

**Comment by cary-ilm** [comment]
I submitted #954 to address these.  I'm not following the logic behind removing last install statement, does #954 do what you recommend? 

I kept the spewage in place for now, but at least made the pkg-config status messages consistently formatted.

**Comment by Anteru** [comment]
Yes, that works for me, thanks :) That said: I'm don't think that's what _you_ want, as in unconditionally disable _all_ install support. I think the optimal solution here would be to put that behind an option. As I see it right now you can't install OpenEXR standalone with #954 applied.
