### ISSUE TITLE
BUILD_SHARED/STATIC should not be automatic.

### ISSUE THREAD

**Issue by meshula** [AcademySoftwareFoundation/openexr#882]
From issue https://github.com/AcademySoftwareFoundation/openexr/issues/881

Please don't set BUILD_SHARED_LIBS if you're not the top-level project. An easy check is to compare the CMAKE_CURRENT_SOURCE_DIR with CMAKE_SOURCE_DIR and not turn on global options if it's a submodule. Instead, please add a prefixed option like OPENEXR_BUILD_SHARED or similar. That should be fairly easy to use given ILMBASE_DEFINE_LIBRARY is the entry point for library definitions, and you can simply select the library type there:

```cmake
  if(OPENEXR_BUILD_SHARED_LIBS)
    set(OPENEXR_LIB_TYPE SHARED)
  else()
    set(OPENEXR_LIB_TYPE STATIC)
  endif()
  add_library(${objlib} ${OPENEXR_LIB_TYPE}
    ${ILMBASE_CURLIB_HEADERS}
    ${ILMBASE_CURLIB_SOURCES})
```

For issues resulting from confusion or issues resulting from building both static and dynamic libs see also:

https://github.com/AcademySoftwareFoundation/openexr/issues/748
https://github.com/AcademySoftwareFoundation/openexr/issues/833
https://github.com/AcademySoftwareFoundation/openexr/issues/856
https://github.com/AcademySoftwareFoundation/openexr/issues/871

If we remove heuristics about which build to make, and make the shared library automatic on linux, otherwise default to static, the majority of first-time user problems will be resolved.

**Comment by lgritz** [comment]
The SHARED/STATIC is an optional argument to add_library. If not specified, it will just use the global BUILD_SHARED_LIBS.

Is it better to just not specify it at all, in which case we would inherit from the parent project, or whatever a user specifes with -DBUILD_SHARED_LIBS at config time?

What is the case for having OPENEXR_BUILD_SHARED_LIBS to control this separately from the rest of the project?

**Comment by lgritz** [comment]
If the only real offense is that we have

    option(BUILD_SHARED_LIBS "Build shared library" ON)

and we shouldn't be *setting* that if we're not the top-level project, then is it not sufficient to simply surround that one line in an `if` testing whether we're the top level and everything else can remain the same or even reduce complexity to use this one variable?

**Comment by meshula** [comment]
I believe you are getting to the heart of it.

- we have an externally visible cmake options with the very generic name BUILD_SHARED_LIBS, and a naming convention defying one called INSTALL_OPENEXR_EXAMPLES.

- our toolchain files referencenon-existent variables, including OPENEXR_BUILD_STATIC and BUILD_ILMBASE_STATIC, and a bazillion FLTK variables.

- the OPENEXR_BUILD_BOTH_STATIC_SHARED results in complex logic in a number of places. Assuming that everything is currently correct, it is easy to imagine breaking it unintentionally moving forward. For example:

```cmake
  if(OPENEXR_CURLIB_PRIV_EXPORT AND BUILD_SHARED_LIBS)
    target_compile_definitions(${objlib} PRIVATE ${OPENEXR_CURLIB_PRIV_EXPORT})
    if(WIN32 AND NOT OPENEXR_BUILD_BOTH_STATIC_SHARED)
      target_compile_definitions(${objlib} PUBLIC OPENEXR_DLL)
    endif()
  endif()
```
If we are building shared, and not also building static, define OPENEXR_DLL in the compile definitions. I'm not sure how to parse the intent and validity of that.

I think eliminating the notion of BOTH_STATIC_SHARED will help a lot in being able to consistently build properly.

**Comment by lgritz** [comment]
I don't think we should support both shared and static in the same build configuration. Too much brittle complexity. Let the tiny minority of people who need both just do two builds, just like we do for people who want both debug and optimized builds. It's easy to write a simple script to drive building all these variants from the outside of our build system.
