### ISSUE TITLE
NOTICE CMake message outputs to STDERR, failing CI

### ISSUE THREAD

**Issue by ScatteredRay** [AcademySoftwareFoundation/openexr#891]
It's pretty common for CI to take any output to STDERR as a build failure. in IlmBase/config/CMakeLists.txt if pkg-config isn't enabled, this message is fired:

`  message(NOTICE "-- WARNING pkg-config generation disabled")`

NOTICE on cmake outputs to STDERR, perhaps this should be changed to WARNING?

**Comment by cary-ilm** [comment]
See #899.

**Comment by cary-ilm** [comment]
Should be resolved by #899, thanks for the pointer.
