### ISSUE TITLE
ImfCompressor.h missing from header section of CMakeLists.txt

### ISSUE THREAD

**Issue by luke-titley** [AcademySoftwareFoundation/openexr#947]
In the HEADERS section of this file.
ImfCompressor.h is missing.
https://github.com/AcademySoftwareFoundation/openexr/blob/master/src/lib/OpenEXR/CMakeLists.txt

You can't include ImfB44Compressor.h without it.

**Comment by peterhillman** [comment]
Hi @luke-titley, Good catch! Do you need ImfB44Compressor.h for anything? I suspect it was accidentally included, and is not intended to be an installed public header file. Other files such as ImfZipCompressor.h are not installed

**Comment by luke-titley** [comment]
No I don't need it. I've been testing a c api generator using openexr and I came across this.

**Comment by meshula** [comment]
closed by https://github.com/AcademySoftwareFoundation/openexr/pull/950
