### ISSUE TITLE
Importing openEXR 

### ISSUE THREAD

**Issue by Imthiaaz** [AcademySoftwareFoundation/openexr#985]
I'm currently working on windows 10 
Python 3.7.
I try to add openEXR through pip install which ended up in error,
Then I manually downloaded openEXR 2.5 Zip file  package from GitHub 
Can anyone explain how to add those zip file to python packages and to import it clearly I'm totally stuck and I can't understand the steps given in GitHub.

**Comment by meshula** [comment]
Hi there, thanks for trying out OpenEXR! The python bindings available through pip are a different project. This is the C++ OpenEXR project, which those python bindings use. The maintainers of the python bindings might be able to help you in their issues page, which you can find here: 

https://github.com/jamesbowman/openexrpython
